/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.monarkmarkets.api.primary.webapi.api;

import com.fasterxml.jackson.core.type.TypeReference;
import com.monarkmarkets.api.primary.webapi.invoker.ApiClient;
import com.monarkmarkets.api.primary.webapi.invoker.ApiException;
import com.monarkmarkets.api.primary.webapi.invoker.BaseApi;
import com.monarkmarkets.api.primary.webapi.invoker.Configuration;
import com.monarkmarkets.api.primary.webapi.invoker.Pair;
import com.monarkmarkets.api.primary.webapi.model.FinancialInstitution;
import com.monarkmarkets.api.primary.webapi.model.FinancialInstitutionApiResponse;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;
import java.util.UUID;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class FinancialInstitutionApi extends BaseApi {

  public FinancialInstitutionApi() {
    super(Configuration.getDefaultApiClient());
  }

  public FinancialInstitutionApi(ApiClient apiClient) {
    super(apiClient);
  }

  /**
   * Gets all Financial Institutions, optionally filtered by Partner ID.
   * 
   * @param page  (optional, default to 1)
   * @param pageSize  (optional, default to 25)
   * @param sortOrder  (optional, default to Descending)
   * @return FinancialInstitutionApiResponse
   * @throws ApiException if fails to make API call
   */
  public FinancialInstitutionApiResponse primaryV1FinancialInstitutionGet(@jakarta.annotation.Nullable Integer page, @jakarta.annotation.Nullable Integer pageSize, @jakarta.annotation.Nullable String sortOrder) throws ApiException {
    return this.primaryV1FinancialInstitutionGet(page, pageSize, sortOrder, Collections.emptyMap());
  }


  /**
   * Gets all Financial Institutions, optionally filtered by Partner ID.
   * 
   * @param page  (optional, default to 1)
   * @param pageSize  (optional, default to 25)
   * @param sortOrder  (optional, default to Descending)
   * @param additionalHeaders additionalHeaders for this call
   * @return FinancialInstitutionApiResponse
   * @throws ApiException if fails to make API call
   */
  public FinancialInstitutionApiResponse primaryV1FinancialInstitutionGet(@jakarta.annotation.Nullable Integer page, @jakarta.annotation.Nullable Integer pageSize, @jakarta.annotation.Nullable String sortOrder, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/primary/v1/financial-institution";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("page", page));
    localVarQueryParams.addAll(apiClient.parameterToPair("pageSize", pageSize));
    localVarQueryParams.addAll(apiClient.parameterToPair("sortOrder", sortOrder));
    
    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "Bearer" };

    TypeReference<FinancialInstitutionApiResponse> localVarReturnType = new TypeReference<FinancialInstitutionApiResponse>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Gets a Financial Institution by ID.
   * 
   * @param id ID of the Financial Institution to retrieve. (required)
   * @return FinancialInstitution
   * @throws ApiException if fails to make API call
   */
  public FinancialInstitution primaryV1FinancialInstitutionIdGet(@jakarta.annotation.Nonnull UUID id) throws ApiException {
    return this.primaryV1FinancialInstitutionIdGet(id, Collections.emptyMap());
  }


  /**
   * Gets a Financial Institution by ID.
   * 
   * @param id ID of the Financial Institution to retrieve. (required)
   * @param additionalHeaders additionalHeaders for this call
   * @return FinancialInstitution
   * @throws ApiException if fails to make API call
   */
  public FinancialInstitution primaryV1FinancialInstitutionIdGet(@jakarta.annotation.Nonnull UUID id, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling primaryV1FinancialInstitutionIdGet");
    }
    
    // create path and map variables
    String localVarPath = "/primary/v1/financial-institution/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    
    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "Bearer" };

    TypeReference<FinancialInstitution> localVarReturnType = new TypeReference<FinancialInstitution>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  @Override
  public <T> T invokeAPI(String url, String method, Object request, TypeReference<T> returnType, Map<String, String> additionalHeaders) throws ApiException {
    String localVarPath = url.replace(apiClient.getBaseURL(), "");
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarHeaderParams.putAll(additionalHeaders);

    final String[] localVarAccepts = {
      "application/json"
    };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "Bearer" };

    return apiClient.invokeAPI(
      localVarPath,
        method,
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        request,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        returnType
    );
  }
}
