package com.monarkmarkets.dtos.preipocompanyspv;

public enum ExemptionClaimed {
	RULE_504_B_1_NOT_I_II_III,
	RULE_504_B_1_I,
	RULE_504_B_1_II,
	RULE_504_B_1_III,
	RULE_506_B,
	RULE_506_C,
	SECURITIES_ACT_SECTION_4_A_5,
	SECURITIES_ACT_SECTION_3_C_1,
	SECURITIES_ACT_SECTION_3_C_2,
	SECURITIES_ACT_SECTION_3_C_3,
	SECURITIES_ACT_SECTION_3_C_4,
	SECURITIES_ACT_SECTION_3_C_5,
	SECURITIES_ACT_SECTION_3_C_6,
	SECURITIES_ACT_SECTION_3_C_7,
	SECURITIES_ACT_SECTION_3_C_9,
	SECURITIES_ACT_SECTION_3_C_10,
	SECURITIES_ACT_SECTION_3_C_11,
	SECURITIES_ACT_SECTION_3_C_12,
	SECURITIES_ACT_SECTION_3_C_13,
	SECURITIES_ACT_SECTION_3_C_14
}