package com.monarkmarkets.dtos.preipocompanyspv;

/**
 * Enum representing the lifecycle stage of a PreIPOCompanySPV.
 */
public enum MonarkStage {
	DRAFT,
	WAITING_MONARK_REVIEW,
	FUND_ADMIN_REVIEW,
	FUND_ADMIN_APPROVED,
	PRIMARY_FUNDRAISE,
	PRE_CLOSE_REVIEW,
	CLOSE_REQUESTED,
	CLOSE_IN_PROCESS,
	FUNDS_SENT_TO_TARGET,
	CLOSED,
	REGULATORY_HOLD_PERIOD,
	ACTIVELY_TRADING,
	CLOSE_FAILED,
	HALTED,
	LIQUIDATION,
	DISSOLVED
}
