package com.monarkmarkets.dtos.preipocompanyspv;

public enum MonarkStage {
	DRAFT,
	WAITING_MONARK_REVIEW,
	FUND_ADMIN_REVIEW,
	PRIMARY_FUNDRAISE,
	MONARK_DILIGENCE,
	CLOSE_REQUESTED,
	CLOSE_IN_PROCESS,
	FUNDS_SENT_TO_TARGET,
	CLOSED,
	REGULATORY_HOLD_PERIOD,
	ACTIVELY_TRADING,
	CLOSE_FAILED,
	HALTED,
	LIQUIDATION,
	DISSOLVED
}