package com.monarkmarkets.dtos.investor;

public enum AccreditationStatus {
//	NET_WORTH_GT_1M, // Commented out until new version is deployed in demo with fix
	INDIVIDUAL_INCOME_GT_200K,
	JOINT_INCOME_GT_300K,
	PROFESSION_DESIGNATION,
	TRUST_GT_5M,
	GRANTORS_ACCREDITED,
	EQUITY_OWNERS_ACCREDITED,
	TOTAL_ASSETS_GT_5M,
	INVESTMENT_COMPANY,
	SEC_OR_EXEMPT_ADVISOR,
	KNOWLEDGEABLE_EMPLOYEE,
	KNOWLEDGEABLE_EXECUTIVE,
	FAMILY_OFFICE_GT_5M
}
