package com.monarkmarkets.dtos.investor;

/**
 * Type of the entity.
 */
public enum EntityType {
	SOLE_PROPRIETOR,
	SINGLE_MEMBER_LLC,
	LLC,
	PARTNERSHIP,
	C_CORPORATION,
	S_CORPORATION,
	TRUST,
	IRA_OR_TAX_EXEMPT,
	NON_US_CORPORATION,
	PRIVATE_LIMITED_COMPANY,
	PUBLIC_LIMITED_COMPANY,
	TAX_EXEMPT_ENTITY,
	FOREIGN_TRUST,
	OTHER
}
