package com.monarkmarkets.dtos.investor;

public enum QualificationStatus {
	QUALIFIED_PURCHASER_ALL_BENEFICIAL_OWNERS,
	QUALIFIED_PURCHASER_GT_25M,
	QUALIFIED_PURCHASER,
	QUALIFIED_CLIENT,
	QUALIFIED_CLIENT_NET_WORTH,
	QUALIFIED_CLIENT_TOTAL_INVEST_WITH_DL,
	TRUSTEE_QUALIFIED_PURCHASER,
	SETTLOR_GT_5M,
	KNOWLEDGEABLE_EMPLOYEE,
	KNOWLEDGEABLE_EXECUTIVE,
	FAMILY_OFFICE_GT_5M
}
