package com.monarkmarkets.dtos.preipocompanynews;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.UUID;

/**
 * DTO representing PreIPOCompanyNews.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PreIPOCompanyNews {

	/**
	 * The unique ID attached to this news object.
	 */
	private UUID id;

	/**
	 * The unique ID of the PreIPOCompany associated with the news.
	 */
	private UUID preIPOCompanyId;

	/**
	 * The ID for this news object, generated by our third-party data provider.
	 */
	private String newsId;

	/**
	 * Link to the news.
	 */
	private String link;

	/**
	 * The headline of the news.
	 */
	private String headline;

	/**
	 * Metadata of the news.
	 */
	private String description;

	/**
	 * The source of the news.
	 */
	private String source;

	/**
	 * The release date of the news.
	 */
	private String releaseDate;

	/**
	 * A list of articles associated with the news.
	 */
	private List<PreIPOCompanyNewsArticle> articles;
}
