/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Create the Questionnaire answer.
 */
@JsonPropertyOrder({
  CreateQuestionnaireAnswer.JSON_PROPERTY_QUESTIONNAIRE_ID,
  CreateQuestionnaireAnswer.JSON_PROPERTY_INVESTOR_ID,
  CreateQuestionnaireAnswer.JSON_PROPERTY_CREATE_QUESTION_ANSWERS
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateQuestionnaireAnswer {
  public static final String JSON_PROPERTY_QUESTIONNAIRE_ID = "questionnaireId";
  @jakarta.annotation.Nonnull
  private UUID questionnaireId;

  public static final String JSON_PROPERTY_INVESTOR_ID = "investorId";
  @jakarta.annotation.Nonnull
  private UUID investorId;

  public static final String JSON_PROPERTY_CREATE_QUESTION_ANSWERS = "createQuestionAnswers";
  @jakarta.annotation.Nonnull
  private List<CreateQuestionnaireQuestionAnswer> createQuestionAnswers = new ArrayList<>();

  public CreateQuestionnaireAnswer() {
  }

  public CreateQuestionnaireAnswer questionnaireId(@jakarta.annotation.Nonnull UUID questionnaireId) {
    
    this.questionnaireId = questionnaireId;
    return this;
  }

  /**
   * Unique ID of the Questionnaire being answered.
   * @return questionnaireId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUESTIONNAIRE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getQuestionnaireId() {
    return questionnaireId;
  }


  @JsonProperty(JSON_PROPERTY_QUESTIONNAIRE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuestionnaireId(@jakarta.annotation.Nonnull UUID questionnaireId) {
    this.questionnaireId = questionnaireId;
  }

  public CreateQuestionnaireAnswer investorId(@jakarta.annotation.Nonnull UUID investorId) {
    
    this.investorId = investorId;
    return this;
  }

  /**
   * The linked InvestorId.
   * @return investorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getInvestorId() {
    return investorId;
  }


  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvestorId(@jakarta.annotation.Nonnull UUID investorId) {
    this.investorId = investorId;
  }

  public CreateQuestionnaireAnswer createQuestionAnswers(@jakarta.annotation.Nonnull List<CreateQuestionnaireQuestionAnswer> createQuestionAnswers) {
    
    this.createQuestionAnswers = createQuestionAnswers;
    return this;
  }

  public CreateQuestionnaireAnswer addCreateQuestionAnswersItem(CreateQuestionnaireQuestionAnswer createQuestionAnswersItem) {
    if (this.createQuestionAnswers == null) {
      this.createQuestionAnswers = new ArrayList<>();
    }
    this.createQuestionAnswers.add(createQuestionAnswersItem);
    return this;
  }

  /**
   * Pairing of all the Questions and Investor-provided responses associated with the Questionnaire.
   * @return createQuestionAnswers
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATE_QUESTION_ANSWERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateQuestionnaireQuestionAnswer> getCreateQuestionAnswers() {
    return createQuestionAnswers;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_QUESTION_ANSWERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreateQuestionAnswers(@jakarta.annotation.Nonnull List<CreateQuestionnaireQuestionAnswer> createQuestionAnswers) {
    this.createQuestionAnswers = createQuestionAnswers;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateQuestionnaireAnswer createQuestionnaireAnswer = (CreateQuestionnaireAnswer) o;
    return Objects.equals(this.questionnaireId, createQuestionnaireAnswer.questionnaireId) &&
        Objects.equals(this.investorId, createQuestionnaireAnswer.investorId) &&
        Objects.equals(this.createQuestionAnswers, createQuestionnaireAnswer.createQuestionAnswers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(questionnaireId, investorId, createQuestionAnswers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateQuestionnaireAnswer {\n");
    sb.append("    questionnaireId: ").append(toIndentedString(questionnaireId)).append("\n");
    sb.append("    investorId: ").append(toIndentedString(investorId)).append("\n");
    sb.append("    createQuestionAnswers: ").append(toIndentedString(createQuestionAnswers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `questionnaireId` to the URL query string
    if (getQuestionnaireId() != null) {
      try {
        joiner.add(String.format("%squestionnaireId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQuestionnaireId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `investorId` to the URL query string
    if (getInvestorId() != null) {
      try {
        joiner.add(String.format("%sinvestorId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInvestorId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `createQuestionAnswers` to the URL query string
    if (getCreateQuestionAnswers() != null) {
      for (int i = 0; i < getCreateQuestionAnswers().size(); i++) {
        if (getCreateQuestionAnswers().get(i) != null) {
          joiner.add(getCreateQuestionAnswers().get(i).toUrlQueryString(String.format("%screateQuestionAnswers%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

