/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * CreateIndividualEntityInvestors
 */
@JsonPropertyOrder({
  CreateIndividualEntityInvestors.JSON_PROPERTY_INDIVIDUAL_INVESTORS
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateIndividualEntityInvestors {
  public static final String JSON_PROPERTY_INDIVIDUAL_INVESTORS = "individualInvestors";
  @jakarta.annotation.Nullable
  private List<IndividualEntityInvestorBase> individualInvestors;

  public CreateIndividualEntityInvestors() {
  }

  public CreateIndividualEntityInvestors individualInvestors(@jakarta.annotation.Nullable List<IndividualEntityInvestorBase> individualInvestors) {
    
    this.individualInvestors = individualInvestors;
    return this;
  }

  public CreateIndividualEntityInvestors addIndividualInvestorsItem(IndividualEntityInvestorBase individualInvestorsItem) {
    if (this.individualInvestors == null) {
      this.individualInvestors = new ArrayList<>();
    }
    this.individualInvestors.add(individualInvestorsItem);
    return this;
  }

  /**
   * Get individualInvestors
   * @return individualInvestors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IndividualEntityInvestorBase> getIndividualInvestors() {
    return individualInvestors;
  }


  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTORS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndividualInvestors(@jakarta.annotation.Nullable List<IndividualEntityInvestorBase> individualInvestors) {
    this.individualInvestors = individualInvestors;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateIndividualEntityInvestors createIndividualEntityInvestors = (CreateIndividualEntityInvestors) o;
    return Objects.equals(this.individualInvestors, createIndividualEntityInvestors.individualInvestors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individualInvestors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateIndividualEntityInvestors {\n");
    sb.append("    individualInvestors: ").append(toIndentedString(individualInvestors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `individualInvestors` to the URL query string
    if (getIndividualInvestors() != null) {
      for (int i = 0; i < getIndividualInvestors().size(); i++) {
        if (getIndividualInvestors().get(i) != null) {
          joiner.add(getIndividualInvestors().get(i).toUrlQueryString(String.format("%sindividualInvestors%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}

