/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * CreateInvestorSubscription
 */
@JsonPropertyOrder({
  CreateInvestorSubscription.JSON_PROPERTY_PRE_I_P_O_COMPANY_S_P_V_ID,
  CreateInvestorSubscription.JSON_PROPERTY_INVESTOR_ID,
  CreateInvestorSubscription.JSON_PROPERTY_AMOUNT_RESERVED_DOLLARS,
  CreateInvestorSubscription.JSON_PROPERTY_AMOUNT_RESERVED_SHARES
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class CreateInvestorSubscription {
  public static final String JSON_PROPERTY_PRE_I_P_O_COMPANY_S_P_V_ID = "preIPOCompanySPVId";
  @jakarta.annotation.Nonnull
  private UUID preIPOCompanySPVId;

  public static final String JSON_PROPERTY_INVESTOR_ID = "investorId";
  @jakarta.annotation.Nonnull
  private UUID investorId;

  public static final String JSON_PROPERTY_AMOUNT_RESERVED_DOLLARS = "amountReservedDollars";
  @jakarta.annotation.Nonnull
  private Double amountReservedDollars;

  public static final String JSON_PROPERTY_AMOUNT_RESERVED_SHARES = "amountReservedShares";
  @jakarta.annotation.Nonnull
  private Integer amountReservedShares;

  public CreateInvestorSubscription() {
  }

  public CreateInvestorSubscription preIPOCompanySPVId(@jakarta.annotation.Nonnull UUID preIPOCompanySPVId) {
    
    this.preIPOCompanySPVId = preIPOCompanySPVId;
    return this;
  }

  /**
   * The SPV ID that this Subscription relates to.
   * @return preIPOCompanySPVId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_S_P_V_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getPreIPOCompanySPVId() {
    return preIPOCompanySPVId;
  }


  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_S_P_V_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreIPOCompanySPVId(@jakarta.annotation.Nonnull UUID preIPOCompanySPVId) {
    this.preIPOCompanySPVId = preIPOCompanySPVId;
  }

  public CreateInvestorSubscription investorId(@jakarta.annotation.Nonnull UUID investorId) {
    
    this.investorId = investorId;
    return this;
  }

  /**
   * ID of the Investor associated with this InvestorSubscription.
   * @return investorId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getInvestorId() {
    return investorId;
  }


  @JsonProperty(JSON_PROPERTY_INVESTOR_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvestorId(@jakarta.annotation.Nonnull UUID investorId) {
    this.investorId = investorId;
  }

  public CreateInvestorSubscription amountReservedDollars(@jakarta.annotation.Nonnull Double amountReservedDollars) {
    
    this.amountReservedDollars = amountReservedDollars;
    return this;
  }

  /**
   * Describes the amount, in dollars, an Investor intends to invest into an SPV.
   * minimum: 0
   * @return amountReservedDollars
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_RESERVED_DOLLARS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getAmountReservedDollars() {
    return amountReservedDollars;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_RESERVED_DOLLARS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountReservedDollars(@jakarta.annotation.Nonnull Double amountReservedDollars) {
    this.amountReservedDollars = amountReservedDollars;
  }

  public CreateInvestorSubscription amountReservedShares(@jakarta.annotation.Nonnull Integer amountReservedShares) {
    
    this.amountReservedShares = amountReservedShares;
    return this;
  }

  /**
   * Describes how many underlying shares in the pre-IPO company are associated with this InvestorSubscription. This must be a whole number of shares.
   * minimum: 0
   * @return amountReservedShares
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_RESERVED_SHARES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountReservedShares() {
    return amountReservedShares;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_RESERVED_SHARES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountReservedShares(@jakarta.annotation.Nonnull Integer amountReservedShares) {
    this.amountReservedShares = amountReservedShares;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInvestorSubscription createInvestorSubscription = (CreateInvestorSubscription) o;
    return Objects.equals(this.preIPOCompanySPVId, createInvestorSubscription.preIPOCompanySPVId) &&
        Objects.equals(this.investorId, createInvestorSubscription.investorId) &&
        Objects.equals(this.amountReservedDollars, createInvestorSubscription.amountReservedDollars) &&
        Objects.equals(this.amountReservedShares, createInvestorSubscription.amountReservedShares);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preIPOCompanySPVId, investorId, amountReservedDollars, amountReservedShares);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInvestorSubscription {\n");
    sb.append("    preIPOCompanySPVId: ").append(toIndentedString(preIPOCompanySPVId)).append("\n");
    sb.append("    investorId: ").append(toIndentedString(investorId)).append("\n");
    sb.append("    amountReservedDollars: ").append(toIndentedString(amountReservedDollars)).append("\n");
    sb.append("    amountReservedShares: ").append(toIndentedString(amountReservedShares)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `preIPOCompanySPVId` to the URL query string
    if (getPreIPOCompanySPVId() != null) {
      try {
        joiner.add(String.format("%spreIPOCompanySPVId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPreIPOCompanySPVId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `investorId` to the URL query string
    if (getInvestorId() != null) {
      try {
        joiner.add(String.format("%sinvestorId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInvestorId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `amountReservedDollars` to the URL query string
    if (getAmountReservedDollars() != null) {
      try {
        joiner.add(String.format("%samountReservedDollars%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAmountReservedDollars()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `amountReservedShares` to the URL query string
    if (getAmountReservedShares() != null) {
      try {
        joiner.add(String.format("%samountReservedShares%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAmountReservedShares()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

