/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Represents a fee structure that can be associated with either a registered fund or a share class.
 */
@JsonPropertyOrder({
  FeeStructure.JSON_PROPERTY_ID,
  FeeStructure.JSON_PROPERTY_SHARE_CLASS_ID,
  FeeStructure.JSON_PROPERTY_REGISTERED_FUND_ID,
  FeeStructure.JSON_PROPERTY_FEE_TYPE,
  FeeStructure.JSON_PROPERTY_FEE_VALUE,
  FeeStructure.JSON_PROPERTY_DESCRIPTION
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class FeeStructure {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_SHARE_CLASS_ID = "shareClassId";
  @jakarta.annotation.Nullable
  private UUID shareClassId;

  public static final String JSON_PROPERTY_REGISTERED_FUND_ID = "registeredFundId";
  @jakarta.annotation.Nullable
  private UUID registeredFundId;

  /**
   * Type of fee
   */
  public enum FeeTypeEnum {
    MANAGEMENT_FEE(String.valueOf("MANAGEMENT_FEE")),
    
    PERFORMANCE_FEE(String.valueOf("PERFORMANCE_FEE")),
    
    DISTRIBUTION_FEE(String.valueOf("DISTRIBUTION_FEE")),
    
    SALES_LOAD(String.valueOf("SALES_LOAD")),
    
    EARLY_REDEMPTION_FEE(String.valueOf("EARLY_REDEMPTION_FEE"));

    private String value;

    FeeTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FeeTypeEnum fromValue(String value) {
      for (FeeTypeEnum b : FeeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FEE_TYPE = "feeType";
  @jakarta.annotation.Nonnull
  private FeeTypeEnum feeType;

  public static final String JSON_PROPERTY_FEE_VALUE = "feeValue";
  @jakarta.annotation.Nonnull
  private Double feeValue;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public FeeStructure() {
  }

  public FeeStructure id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID of the fee structure.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public FeeStructure shareClassId(@jakarta.annotation.Nullable UUID shareClassId) {
    
    this.shareClassId = shareClassId;
    return this;
  }

  /**
   * Optional unique ID of the Share Class associated with this Fee Structure.
   * @return shareClassId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARE_CLASS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getShareClassId() {
    return shareClassId;
  }


  @JsonProperty(JSON_PROPERTY_SHARE_CLASS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShareClassId(@jakarta.annotation.Nullable UUID shareClassId) {
    this.shareClassId = shareClassId;
  }

  public FeeStructure registeredFundId(@jakarta.annotation.Nullable UUID registeredFundId) {
    
    this.registeredFundId = registeredFundId;
    return this;
  }

  /**
   * Optional unique ID of the Registered Fund associated with this Fee Structure.
   * @return registeredFundId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTERED_FUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getRegisteredFundId() {
    return registeredFundId;
  }


  @JsonProperty(JSON_PROPERTY_REGISTERED_FUND_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegisteredFundId(@jakarta.annotation.Nullable UUID registeredFundId) {
    this.registeredFundId = registeredFundId;
  }

  public FeeStructure feeType(@jakarta.annotation.Nonnull FeeTypeEnum feeType) {
    
    this.feeType = feeType;
    return this;
  }

  /**
   * Type of fee
   * @return feeType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FeeTypeEnum getFeeType() {
    return feeType;
  }


  @JsonProperty(JSON_PROPERTY_FEE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeeType(@jakarta.annotation.Nonnull FeeTypeEnum feeType) {
    this.feeType = feeType;
  }

  public FeeStructure feeValue(@jakarta.annotation.Nonnull Double feeValue) {
    
    this.feeValue = feeValue;
    return this;
  }

  /**
   * Fee value, typically a percentage
   * @return feeValue
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FEE_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getFeeValue() {
    return feeValue;
  }


  @JsonProperty(JSON_PROPERTY_FEE_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFeeValue(@jakarta.annotation.Nonnull Double feeValue) {
    this.feeValue = feeValue;
  }

  public FeeStructure description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Text field used to describe the fee structure.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeStructure feeStructure = (FeeStructure) o;
    return Objects.equals(this.id, feeStructure.id) &&
        Objects.equals(this.shareClassId, feeStructure.shareClassId) &&
        Objects.equals(this.registeredFundId, feeStructure.registeredFundId) &&
        Objects.equals(this.feeType, feeStructure.feeType) &&
        Objects.equals(this.feeValue, feeStructure.feeValue) &&
        Objects.equals(this.description, feeStructure.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shareClassId, registeredFundId, feeType, feeValue, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeStructure {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shareClassId: ").append(toIndentedString(shareClassId)).append("\n");
    sb.append("    registeredFundId: ").append(toIndentedString(registeredFundId)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("    feeValue: ").append(toIndentedString(feeValue)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shareClassId` to the URL query string
    if (getShareClassId() != null) {
      try {
        joiner.add(String.format("%sshareClassId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShareClassId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `registeredFundId` to the URL query string
    if (getRegisteredFundId() != null) {
      try {
        joiner.add(String.format("%sregisteredFundId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRegisteredFundId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `feeType` to the URL query string
    if (getFeeType() != null) {
      try {
        joiner.add(String.format("%sfeeType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFeeType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `feeValue` to the URL query string
    if (getFeeValue() != null) {
      try {
        joiner.add(String.format("%sfeeValue%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFeeValue()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

