/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * FinancialAdvisor represents the financial advisor information.
 */
@JsonPropertyOrder({
  FinancialAdvisor.JSON_PROPERTY_ID,
  FinancialAdvisor.JSON_PROPERTY_FINANCIAL_INSTITUTION_ID,
  FinancialAdvisor.JSON_PROPERTY_CRD_NUMBER,
  FinancialAdvisor.JSON_PROPERTY_IARD_NUMBER,
  FinancialAdvisor.JSON_PROPERTY_FIRST_NAME,
  FinancialAdvisor.JSON_PROPERTY_MIDDLE_NAME,
  FinancialAdvisor.JSON_PROPERTY_LAST_NAME,
  FinancialAdvisor.JSON_PROPERTY_MAILING_COUNTRY_CODE,
  FinancialAdvisor.JSON_PROPERTY_BRANCH_NUMBER,
  FinancialAdvisor.JSON_PROPERTY_PREFIX,
  FinancialAdvisor.JSON_PROPERTY_BROKER
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class FinancialAdvisor {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_FINANCIAL_INSTITUTION_ID = "financialInstitutionId";
  @jakarta.annotation.Nullable
  private UUID financialInstitutionId;

  public static final String JSON_PROPERTY_CRD_NUMBER = "crdNumber";
  @jakarta.annotation.Nullable
  private String crdNumber;

  public static final String JSON_PROPERTY_IARD_NUMBER = "iardNumber";
  @jakarta.annotation.Nullable
  private String iardNumber;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_MIDDLE_NAME = "middleName";
  @jakarta.annotation.Nullable
  private String middleName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @jakarta.annotation.Nullable
  private String lastName;

  public static final String JSON_PROPERTY_MAILING_COUNTRY_CODE = "mailingCountryCode";
  @jakarta.annotation.Nullable
  private String mailingCountryCode;

  public static final String JSON_PROPERTY_BRANCH_NUMBER = "branchNumber";
  @jakarta.annotation.Nullable
  private String branchNumber;

  public static final String JSON_PROPERTY_PREFIX = "prefix";
  @jakarta.annotation.Nullable
  private String prefix;

  public static final String JSON_PROPERTY_BROKER = "broker";
  @jakarta.annotation.Nullable
  private String broker;

  public FinancialAdvisor() {
  }

  public FinancialAdvisor id(@jakarta.annotation.Nullable UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Gets or sets id represents the unique id of the Financial Advisor on the internal system.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }

  public FinancialAdvisor financialInstitutionId(@jakarta.annotation.Nullable UUID financialInstitutionId) {
    
    this.financialInstitutionId = financialInstitutionId;
    return this;
  }

  /**
   * This is the unique identifier of the Institution that the Financial Advisor is attached to.
   * @return financialInstitutionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINANCIAL_INSTITUTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getFinancialInstitutionId() {
    return financialInstitutionId;
  }


  @JsonProperty(JSON_PROPERTY_FINANCIAL_INSTITUTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancialInstitutionId(@jakarta.annotation.Nullable UUID financialInstitutionId) {
    this.financialInstitutionId = financialInstitutionId;
  }

  public FinancialAdvisor crdNumber(@jakarta.annotation.Nullable String crdNumber) {
    
    this.crdNumber = crdNumber;
    return this;
  }

  /**
   * CRD Number of the Financial Advisor.
   * @return crdNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CRD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCrdNumber() {
    return crdNumber;
  }


  @JsonProperty(JSON_PROPERTY_CRD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCrdNumber(@jakarta.annotation.Nullable String crdNumber) {
    this.crdNumber = crdNumber;
  }

  public FinancialAdvisor iardNumber(@jakarta.annotation.Nullable String iardNumber) {
    
    this.iardNumber = iardNumber;
    return this;
  }

  /**
   * IARD Number of the Financial Advisor.
   * @return iardNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IARD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIardNumber() {
    return iardNumber;
  }


  @JsonProperty(JSON_PROPERTY_IARD_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIardNumber(@jakarta.annotation.Nullable String iardNumber) {
    this.iardNumber = iardNumber;
  }

  public FinancialAdvisor firstName(@jakarta.annotation.Nullable String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Financial Advisor first name.
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }

  public FinancialAdvisor middleName(@jakarta.annotation.Nullable String middleName) {
    
    this.middleName = middleName;
    return this;
  }

  /**
   * Financial advisor middle name.
   * @return middleName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMiddleName() {
    return middleName;
  }


  @JsonProperty(JSON_PROPERTY_MIDDLE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMiddleName(@jakarta.annotation.Nullable String middleName) {
    this.middleName = middleName;
  }

  public FinancialAdvisor lastName(@jakarta.annotation.Nullable String lastName) {
    
    this.lastName = lastName;
    return this;
  }

  /**
   * Financial advisor last name.
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }

  public FinancialAdvisor mailingCountryCode(@jakarta.annotation.Nullable String mailingCountryCode) {
    
    this.mailingCountryCode = mailingCountryCode;
    return this;
  }

  /**
   * Financial advisor mailing country code.
   * @return mailingCountryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingCountryCode() {
    return mailingCountryCode;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingCountryCode(@jakarta.annotation.Nullable String mailingCountryCode) {
    this.mailingCountryCode = mailingCountryCode;
  }

  public FinancialAdvisor branchNumber(@jakarta.annotation.Nullable String branchNumber) {
    
    this.branchNumber = branchNumber;
    return this;
  }

  /**
   * Financial Advisor branch number.
   * @return branchNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BRANCH_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBranchNumber() {
    return branchNumber;
  }


  @JsonProperty(JSON_PROPERTY_BRANCH_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBranchNumber(@jakarta.annotation.Nullable String branchNumber) {
    this.branchNumber = branchNumber;
  }

  public FinancialAdvisor prefix(@jakarta.annotation.Nullable String prefix) {
    
    this.prefix = prefix;
    return this;
  }

  /**
   * Prefix for the Financial Advisor.
   * @return prefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPrefix() {
    return prefix;
  }


  @JsonProperty(JSON_PROPERTY_PREFIX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrefix(@jakarta.annotation.Nullable String prefix) {
    this.prefix = prefix;
  }

  public FinancialAdvisor broker(@jakarta.annotation.Nullable String broker) {
    
    this.broker = broker;
    return this;
  }

  /**
   * Financial advisor broker.
   * @return broker
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BROKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getBroker() {
    return broker;
  }


  @JsonProperty(JSON_PROPERTY_BROKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBroker(@jakarta.annotation.Nullable String broker) {
    this.broker = broker;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialAdvisor financialAdvisor = (FinancialAdvisor) o;
    return Objects.equals(this.id, financialAdvisor.id) &&
        Objects.equals(this.financialInstitutionId, financialAdvisor.financialInstitutionId) &&
        Objects.equals(this.crdNumber, financialAdvisor.crdNumber) &&
        Objects.equals(this.iardNumber, financialAdvisor.iardNumber) &&
        Objects.equals(this.firstName, financialAdvisor.firstName) &&
        Objects.equals(this.middleName, financialAdvisor.middleName) &&
        Objects.equals(this.lastName, financialAdvisor.lastName) &&
        Objects.equals(this.mailingCountryCode, financialAdvisor.mailingCountryCode) &&
        Objects.equals(this.branchNumber, financialAdvisor.branchNumber) &&
        Objects.equals(this.prefix, financialAdvisor.prefix) &&
        Objects.equals(this.broker, financialAdvisor.broker);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, financialInstitutionId, crdNumber, iardNumber, firstName, middleName, lastName, mailingCountryCode, branchNumber, prefix, broker);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialAdvisor {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    financialInstitutionId: ").append(toIndentedString(financialInstitutionId)).append("\n");
    sb.append("    crdNumber: ").append(toIndentedString(crdNumber)).append("\n");
    sb.append("    iardNumber: ").append(toIndentedString(iardNumber)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    middleName: ").append(toIndentedString(middleName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    mailingCountryCode: ").append(toIndentedString(mailingCountryCode)).append("\n");
    sb.append("    branchNumber: ").append(toIndentedString(branchNumber)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    broker: ").append(toIndentedString(broker)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `financialInstitutionId` to the URL query string
    if (getFinancialInstitutionId() != null) {
      try {
        joiner.add(String.format("%sfinancialInstitutionId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFinancialInstitutionId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `crdNumber` to the URL query string
    if (getCrdNumber() != null) {
      try {
        joiner.add(String.format("%scrdNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCrdNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `iardNumber` to the URL query string
    if (getIardNumber() != null) {
      try {
        joiner.add(String.format("%siardNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIardNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      try {
        joiner.add(String.format("%sfirstName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFirstName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `middleName` to the URL query string
    if (getMiddleName() != null) {
      try {
        joiner.add(String.format("%smiddleName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMiddleName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      try {
        joiner.add(String.format("%slastName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingCountryCode` to the URL query string
    if (getMailingCountryCode() != null) {
      try {
        joiner.add(String.format("%smailingCountryCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingCountryCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `branchNumber` to the URL query string
    if (getBranchNumber() != null) {
      try {
        joiner.add(String.format("%sbranchNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBranchNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `prefix` to the URL query string
    if (getPrefix() != null) {
      try {
        joiner.add(String.format("%sprefix%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrefix()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `broker` to the URL query string
    if (getBroker() != null) {
      try {
        joiner.add(String.format("%sbroker%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getBroker()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

