/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDate;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * IndividualEntityInvestor
 */
@JsonPropertyOrder({
  IndividualEntityInvestor.JSON_PROPERTY_FIRST_NAME,
  IndividualEntityInvestor.JSON_PROPERTY_LAST_NAME,
  IndividualEntityInvestor.JSON_PROPERTY_IS_U_S_BASED,
  IndividualEntityInvestor.JSON_PROPERTY_DATE_OF_BIRTH,
  IndividualEntityInvestor.JSON_PROPERTY_STREET1,
  IndividualEntityInvestor.JSON_PROPERTY_STREET2,
  IndividualEntityInvestor.JSON_PROPERTY_CITY,
  IndividualEntityInvestor.JSON_PROPERTY_STATE,
  IndividualEntityInvestor.JSON_PROPERTY_ZIP_CODE,
  IndividualEntityInvestor.JSON_PROPERTY_COUNTRY_CODE,
  IndividualEntityInvestor.JSON_PROPERTY_PHONE_COUNTRY_CODE,
  IndividualEntityInvestor.JSON_PROPERTY_PHONE_NUMBER,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_STREET1,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_STREET2,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_ADDRESS_APT_SUITE_NO,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_ADDRESS_CITY,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_ADDRESS_STATE,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_ADDRESS_ZIP_CODE,
  IndividualEntityInvestor.JSON_PROPERTY_MAILING_ADDRESS_COUNTRY,
  IndividualEntityInvestor.JSON_PROPERTY_HAS_BACKUP_WITHHOLDING,
  IndividualEntityInvestor.JSON_PROPERTY_EXEMPT_PAYEE_CODE,
  IndividualEntityInvestor.JSON_PROPERTY_IS_SUBSCRIPTION_ADVISOR_OR_E_R_A,
  IndividualEntityInvestor.JSON_PROPERTY_EMAIL,
  IndividualEntityInvestor.JSON_PROPERTY_TAX_ID,
  IndividualEntityInvestor.JSON_PROPERTY_PASSPORT_NUMBER,
  IndividualEntityInvestor.JSON_PROPERTY_CITIZENSHIP,
  IndividualEntityInvestor.JSON_PROPERTY_QUALIFIED_STATUS,
  IndividualEntityInvestor.JSON_PROPERTY_ENTITY_INVESTOR_TYPE,
  IndividualEntityInvestor.JSON_PROPERTY_PERCENTAGE_OWNED,
  IndividualEntityInvestor.JSON_PROPERTY_ID
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class IndividualEntityInvestor {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @jakarta.annotation.Nullable
  private String lastName;

  public static final String JSON_PROPERTY_IS_U_S_BASED = "isUSBased";
  @jakarta.annotation.Nullable
  private Boolean isUSBased;

  public static final String JSON_PROPERTY_DATE_OF_BIRTH = "dateOfBirth";
  @jakarta.annotation.Nullable
  private LocalDate dateOfBirth;

  public static final String JSON_PROPERTY_STREET1 = "street1";
  @jakarta.annotation.Nullable
  private String street1;

  public static final String JSON_PROPERTY_STREET2 = "street2";
  @jakarta.annotation.Nullable
  private String street2;

  public static final String JSON_PROPERTY_CITY = "city";
  @jakarta.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_ZIP_CODE = "zipCode";
  @jakarta.annotation.Nullable
  private String zipCode;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  @jakarta.annotation.Nullable
  private String countryCode;

  public static final String JSON_PROPERTY_PHONE_COUNTRY_CODE = "phoneCountryCode";
  @jakarta.annotation.Nullable
  private String phoneCountryCode;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  @jakarta.annotation.Nullable
  private String phoneNumber;

  public static final String JSON_PROPERTY_MAILING_STREET1 = "mailingStreet1";
  @jakarta.annotation.Nullable
  private String mailingStreet1;

  public static final String JSON_PROPERTY_MAILING_STREET2 = "mailingStreet2";
  @jakarta.annotation.Nullable
  private String mailingStreet2;

  public static final String JSON_PROPERTY_MAILING_ADDRESS_APT_SUITE_NO = "mailingAddressAptSuiteNo";
  @jakarta.annotation.Nullable
  private String mailingAddressAptSuiteNo;

  public static final String JSON_PROPERTY_MAILING_ADDRESS_CITY = "mailingAddressCity";
  @jakarta.annotation.Nullable
  private String mailingAddressCity;

  public static final String JSON_PROPERTY_MAILING_ADDRESS_STATE = "mailingAddressState";
  @jakarta.annotation.Nullable
  private String mailingAddressState;

  public static final String JSON_PROPERTY_MAILING_ADDRESS_ZIP_CODE = "mailingAddressZipCode";
  @jakarta.annotation.Nullable
  private String mailingAddressZipCode;

  public static final String JSON_PROPERTY_MAILING_ADDRESS_COUNTRY = "mailingAddressCountry";
  @jakarta.annotation.Nullable
  private String mailingAddressCountry;

  public static final String JSON_PROPERTY_HAS_BACKUP_WITHHOLDING = "hasBackupWithholding";
  @jakarta.annotation.Nullable
  private Boolean hasBackupWithholding;

  public static final String JSON_PROPERTY_EXEMPT_PAYEE_CODE = "exemptPayeeCode";
  @jakarta.annotation.Nullable
  private String exemptPayeeCode;

  public static final String JSON_PROPERTY_IS_SUBSCRIPTION_ADVISOR_OR_E_R_A = "isSubscriptionAdvisorOrERA";
  @jakarta.annotation.Nullable
  private Boolean isSubscriptionAdvisorOrERA;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_TAX_ID = "taxId";
  @jakarta.annotation.Nullable
  private String taxId;

  public static final String JSON_PROPERTY_PASSPORT_NUMBER = "passportNumber";
  @jakarta.annotation.Nullable
  private String passportNumber;

  public static final String JSON_PROPERTY_CITIZENSHIP = "citizenship";
  @jakarta.annotation.Nullable
  private String citizenship;

  /**
   * The qualification status of an Investor.
   */
  public enum QualifiedStatusEnum {
    QUALIFIED_PURCHASER(String.valueOf("QUALIFIED_PURCHASER")),
    
    QUALIFIED_CLIENT(String.valueOf("QUALIFIED_CLIENT")),
    
    TRUSTEE_QUALIFIED_PURCHASER(String.valueOf("TRUSTEE_QUALIFIED_PURCHASER")),
    
    KNOWLEDGEABLE_EMPLOYEE(String.valueOf("KNOWLEDGEABLE_EMPLOYEE")),
    
    KNOWLEDGEABLE_EXECUTIVE(String.valueOf("KNOWLEDGEABLE_EXECUTIVE"));

    private String value;

    QualifiedStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static QualifiedStatusEnum fromValue(String value) {
      for (QualifiedStatusEnum b : QualifiedStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_QUALIFIED_STATUS = "qualifiedStatus";
  @jakarta.annotation.Nullable
  private QualifiedStatusEnum qualifiedStatus;

  /**
   * The type of entity investor, if the investor is an entity investor.
   */
  public enum EntityInvestorTypeEnum {
    TRUSTEE(String.valueOf("Trustee")),
    
    UBO(String.valueOf("UBO"));

    private String value;

    EntityInvestorTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EntityInvestorTypeEnum fromValue(String value) {
      for (EntityInvestorTypeEnum b : EntityInvestorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ENTITY_INVESTOR_TYPE = "entityInvestorType";
  @jakarta.annotation.Nullable
  private EntityInvestorTypeEnum entityInvestorType;

  public static final String JSON_PROPERTY_PERCENTAGE_OWNED = "percentageOwned";
  @jakarta.annotation.Nullable
  private Double percentageOwned;

  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public IndividualEntityInvestor() {
  }

  public IndividualEntityInvestor firstName(@jakarta.annotation.Nullable String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * First name of the Investor.
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }

  public IndividualEntityInvestor lastName(@jakarta.annotation.Nullable String lastName) {
    
    this.lastName = lastName;
    return this;
  }

  /**
   * Last name of the Investor.
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }

  public IndividualEntityInvestor isUSBased(@jakarta.annotation.Nullable Boolean isUSBased) {
    
    this.isUSBased = isUSBased;
    return this;
  }

  /**
   * Is the Investor based in the United States?
   * @return isUSBased
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_U_S_BASED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsUSBased() {
    return isUSBased;
  }


  @JsonProperty(JSON_PROPERTY_IS_U_S_BASED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsUSBased(@jakarta.annotation.Nullable Boolean isUSBased) {
    this.isUSBased = isUSBased;
  }

  public IndividualEntityInvestor dateOfBirth(@jakarta.annotation.Nullable LocalDate dateOfBirth) {
    
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * Investor’s date of birth.
   * @return dateOfBirth
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getDateOfBirth() {
    return dateOfBirth;
  }


  @JsonProperty(JSON_PROPERTY_DATE_OF_BIRTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateOfBirth(@jakarta.annotation.Nullable LocalDate dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }

  public IndividualEntityInvestor street1(@jakarta.annotation.Nullable String street1) {
    
    this.street1 = street1;
    return this;
  }

  /**
   * Investor’s primary address.
   * @return street1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStreet1() {
    return street1;
  }


  @JsonProperty(JSON_PROPERTY_STREET1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStreet1(@jakarta.annotation.Nullable String street1) {
    this.street1 = street1;
  }

  public IndividualEntityInvestor street2(@jakarta.annotation.Nullable String street2) {
    
    this.street2 = street2;
    return this;
  }

  /**
   * Investor’s secondary address.
   * @return street2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STREET2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStreet2() {
    return street2;
  }


  @JsonProperty(JSON_PROPERTY_STREET2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreet2(@jakarta.annotation.Nullable String street2) {
    this.street2 = street2;
  }

  public IndividualEntityInvestor city(@jakarta.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * City where the Investor resides.
   * @return city
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCity(@jakarta.annotation.Nullable String city) {
    this.city = city;
  }

  public IndividualEntityInvestor state(@jakarta.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * 2/3 letter state code of the investor. Check https://github.com/country-regions/country-region-data/blob/master/data.json for valid state (region) codes
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(@jakarta.annotation.Nullable String state) {
    this.state = state;
  }

  public IndividualEntityInvestor zipCode(@jakarta.annotation.Nullable String zipCode) {
    
    this.zipCode = zipCode;
    return this;
  }

  /**
   * Zip code of the Investor.
   * @return zipCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getZipCode() {
    return zipCode;
  }


  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setZipCode(@jakarta.annotation.Nullable String zipCode) {
    this.zipCode = zipCode;
  }

  public IndividualEntityInvestor countryCode(@jakarta.annotation.Nullable String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Country code of the investor. Check https://github.com/country-regions/country-region-data/blob/master/data.json for valid country codes.
   * @return countryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }

  public IndividualEntityInvestor phoneCountryCode(@jakarta.annotation.Nullable String phoneCountryCode) {
    
    this.phoneCountryCode = phoneCountryCode;
    return this;
  }

  /**
   * When creating or updating a resource send both phone and phone_country_code or neither. Phone country code is validated against a valid list of phone country codes which you can find here (https://github.com/mukeshsoni/country-telephone-data). Do not include a + (plus sign) at the beginning of this string.
   * @return phoneCountryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhoneCountryCode() {
    return phoneCountryCode;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhoneCountryCode(@jakarta.annotation.Nullable String phoneCountryCode) {
    this.phoneCountryCode = phoneCountryCode;
  }

  public IndividualEntityInvestor phoneNumber(@jakarta.annotation.Nullable String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * An unformatted phone number which does not include country code. Refer to this region data (https://github.com/mukeshsoni/country-telephone-data) to select the correct phone country code. Phone numbers where phone_country_code is \&quot;1\&quot; must have 10 digits.
   * @return phoneNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPhoneNumber(@jakarta.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public IndividualEntityInvestor mailingStreet1(@jakarta.annotation.Nullable String mailingStreet1) {
    
    this.mailingStreet1 = mailingStreet1;
    return this;
  }

  /**
   * Investor’s primary mailing address.
   * @return mailingStreet1
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_STREET1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingStreet1() {
    return mailingStreet1;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_STREET1)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingStreet1(@jakarta.annotation.Nullable String mailingStreet1) {
    this.mailingStreet1 = mailingStreet1;
  }

  public IndividualEntityInvestor mailingStreet2(@jakarta.annotation.Nullable String mailingStreet2) {
    
    this.mailingStreet2 = mailingStreet2;
    return this;
  }

  /**
   * Investor’s secondary mailing address.
   * @return mailingStreet2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_STREET2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMailingStreet2() {
    return mailingStreet2;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_STREET2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailingStreet2(@jakarta.annotation.Nullable String mailingStreet2) {
    this.mailingStreet2 = mailingStreet2;
  }

  public IndividualEntityInvestor mailingAddressAptSuiteNo(@jakarta.annotation.Nullable String mailingAddressAptSuiteNo) {
    
    this.mailingAddressAptSuiteNo = mailingAddressAptSuiteNo;
    return this;
  }

  /**
   * Investor&#39;s primary mailing Apt or Suite Number.
   * @return mailingAddressAptSuiteNo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_APT_SUITE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMailingAddressAptSuiteNo() {
    return mailingAddressAptSuiteNo;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_APT_SUITE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMailingAddressAptSuiteNo(@jakarta.annotation.Nullable String mailingAddressAptSuiteNo) {
    this.mailingAddressAptSuiteNo = mailingAddressAptSuiteNo;
  }

  public IndividualEntityInvestor mailingAddressCity(@jakarta.annotation.Nullable String mailingAddressCity) {
    
    this.mailingAddressCity = mailingAddressCity;
    return this;
  }

  /**
   * Investor&#39;s primary mailing address city.
   * @return mailingAddressCity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingAddressCity() {
    return mailingAddressCity;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingAddressCity(@jakarta.annotation.Nullable String mailingAddressCity) {
    this.mailingAddressCity = mailingAddressCity;
  }

  public IndividualEntityInvestor mailingAddressState(@jakarta.annotation.Nullable String mailingAddressState) {
    
    this.mailingAddressState = mailingAddressState;
    return this;
  }

  /**
   * Investor&#39;s primary mailing address state. See https://github.com/country-regions/country-region-data/blob/master/data.json for valid state codes per country.
   * @return mailingAddressState
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingAddressState() {
    return mailingAddressState;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingAddressState(@jakarta.annotation.Nullable String mailingAddressState) {
    this.mailingAddressState = mailingAddressState;
  }

  public IndividualEntityInvestor mailingAddressZipCode(@jakarta.annotation.Nullable String mailingAddressZipCode) {
    
    this.mailingAddressZipCode = mailingAddressZipCode;
    return this;
  }

  /**
   * Investor&#39;s primary mailing address zip code.
   * @return mailingAddressZipCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingAddressZipCode() {
    return mailingAddressZipCode;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingAddressZipCode(@jakarta.annotation.Nullable String mailingAddressZipCode) {
    this.mailingAddressZipCode = mailingAddressZipCode;
  }

  public IndividualEntityInvestor mailingAddressCountry(@jakarta.annotation.Nullable String mailingAddressCountry) {
    
    this.mailingAddressCountry = mailingAddressCountry;
    return this;
  }

  /**
   * Investor&#39;s primary mailing address country. Check https://github.com/country-regions/country-region-data/blob/master/data.json for valid country codes.
   * @return mailingAddressCountry
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMailingAddressCountry() {
    return mailingAddressCountry;
  }


  @JsonProperty(JSON_PROPERTY_MAILING_ADDRESS_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMailingAddressCountry(@jakarta.annotation.Nullable String mailingAddressCountry) {
    this.mailingAddressCountry = mailingAddressCountry;
  }

  public IndividualEntityInvestor hasBackupWithholding(@jakarta.annotation.Nullable Boolean hasBackupWithholding) {
    
    this.hasBackupWithholding = hasBackupWithholding;
    return this;
  }

  /**
   * Describes if the Investor is subject to backup withholding.
   * @return hasBackupWithholding
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HAS_BACKUP_WITHHOLDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasBackupWithholding() {
    return hasBackupWithholding;
  }


  @JsonProperty(JSON_PROPERTY_HAS_BACKUP_WITHHOLDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasBackupWithholding(@jakarta.annotation.Nullable Boolean hasBackupWithholding) {
    this.hasBackupWithholding = hasBackupWithholding;
  }

  public IndividualEntityInvestor exemptPayeeCode(@jakarta.annotation.Nullable String exemptPayeeCode) {
    
    this.exemptPayeeCode = exemptPayeeCode;
    return this;
  }

  /**
   * Investor’s exempt payee code if the Investor is exempt from backup withholding.
   * @return exemptPayeeCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXEMPT_PAYEE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExemptPayeeCode() {
    return exemptPayeeCode;
  }


  @JsonProperty(JSON_PROPERTY_EXEMPT_PAYEE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExemptPayeeCode(@jakarta.annotation.Nullable String exemptPayeeCode) {
    this.exemptPayeeCode = exemptPayeeCode;
  }

  public IndividualEntityInvestor isSubscriptionAdvisorOrERA(@jakarta.annotation.Nullable Boolean isSubscriptionAdvisorOrERA) {
    
    this.isSubscriptionAdvisorOrERA = isSubscriptionAdvisorOrERA;
    return this;
  }

  /**
   * Is the investor registered as an adviser for the subscription or an exempt reporting adviser?
   * @return isSubscriptionAdvisorOrERA
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_SUBSCRIPTION_ADVISOR_OR_E_R_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsSubscriptionAdvisorOrERA() {
    return isSubscriptionAdvisorOrERA;
  }


  @JsonProperty(JSON_PROPERTY_IS_SUBSCRIPTION_ADVISOR_OR_E_R_A)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsSubscriptionAdvisorOrERA(@jakarta.annotation.Nullable Boolean isSubscriptionAdvisorOrERA) {
    this.isSubscriptionAdvisorOrERA = isSubscriptionAdvisorOrERA;
  }

  public IndividualEntityInvestor email(@jakarta.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Email address associated with an Investor.
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }

  public IndividualEntityInvestor taxId(@jakarta.annotation.Nullable String taxId) {
    
    this.taxId = taxId;
    return this;
  }

  /**
   * Investor’s Social Security Number.
   * @return taxId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTaxId() {
    return taxId;
  }


  @JsonProperty(JSON_PROPERTY_TAX_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTaxId(@jakarta.annotation.Nullable String taxId) {
    this.taxId = taxId;
  }

  public IndividualEntityInvestor passportNumber(@jakarta.annotation.Nullable String passportNumber) {
    
    this.passportNumber = passportNumber;
    return this;
  }

  /**
   * Investor Passport Number. - Only Required for Non-US Investors.
   * @return passportNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PASSPORT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPassportNumber() {
    return passportNumber;
  }


  @JsonProperty(JSON_PROPERTY_PASSPORT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPassportNumber(@jakarta.annotation.Nullable String passportNumber) {
    this.passportNumber = passportNumber;
  }

  public IndividualEntityInvestor citizenship(@jakarta.annotation.Nullable String citizenship) {
    
    this.citizenship = citizenship;
    return this;
  }

  /**
   * Country code of the Investor’s citizenship. Check https://github.com/country-regions/country-region-data/blob/master/data.json for valid country codes
   * @return citizenship
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITIZENSHIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCitizenship() {
    return citizenship;
  }


  @JsonProperty(JSON_PROPERTY_CITIZENSHIP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCitizenship(@jakarta.annotation.Nullable String citizenship) {
    this.citizenship = citizenship;
  }

  public IndividualEntityInvestor qualifiedStatus(@jakarta.annotation.Nullable QualifiedStatusEnum qualifiedStatus) {
    
    this.qualifiedStatus = qualifiedStatus;
    return this;
  }

  /**
   * The qualification status of an Investor.
   * @return qualifiedStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUALIFIED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public QualifiedStatusEnum getQualifiedStatus() {
    return qualifiedStatus;
  }


  @JsonProperty(JSON_PROPERTY_QUALIFIED_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQualifiedStatus(@jakarta.annotation.Nullable QualifiedStatusEnum qualifiedStatus) {
    this.qualifiedStatus = qualifiedStatus;
  }

  public IndividualEntityInvestor entityInvestorType(@jakarta.annotation.Nullable EntityInvestorTypeEnum entityInvestorType) {
    
    this.entityInvestorType = entityInvestorType;
    return this;
  }

  /**
   * The type of entity investor, if the investor is an entity investor.
   * @return entityInvestorType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EntityInvestorTypeEnum getEntityInvestorType() {
    return entityInvestorType;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityInvestorType(@jakarta.annotation.Nullable EntityInvestorTypeEnum entityInvestorType) {
    this.entityInvestorType = entityInvestorType;
  }

  public IndividualEntityInvestor percentageOwned(@jakarta.annotation.Nullable Double percentageOwned) {
    
    this.percentageOwned = percentageOwned;
    return this;
  }

  /**
   * The percentage of the entity owned by the investor.
   * @return percentageOwned
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENTAGE_OWNED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPercentageOwned() {
    return percentageOwned;
  }


  @JsonProperty(JSON_PROPERTY_PERCENTAGE_OWNED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentageOwned(@jakarta.annotation.Nullable Double percentageOwned) {
    this.percentageOwned = percentageOwned;
  }

  public IndividualEntityInvestor id(@jakarta.annotation.Nullable UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Id of the individual investor.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualEntityInvestor individualEntityInvestor = (IndividualEntityInvestor) o;
    return Objects.equals(this.firstName, individualEntityInvestor.firstName) &&
        Objects.equals(this.lastName, individualEntityInvestor.lastName) &&
        Objects.equals(this.isUSBased, individualEntityInvestor.isUSBased) &&
        Objects.equals(this.dateOfBirth, individualEntityInvestor.dateOfBirth) &&
        Objects.equals(this.street1, individualEntityInvestor.street1) &&
        Objects.equals(this.street2, individualEntityInvestor.street2) &&
        Objects.equals(this.city, individualEntityInvestor.city) &&
        Objects.equals(this.state, individualEntityInvestor.state) &&
        Objects.equals(this.zipCode, individualEntityInvestor.zipCode) &&
        Objects.equals(this.countryCode, individualEntityInvestor.countryCode) &&
        Objects.equals(this.phoneCountryCode, individualEntityInvestor.phoneCountryCode) &&
        Objects.equals(this.phoneNumber, individualEntityInvestor.phoneNumber) &&
        Objects.equals(this.mailingStreet1, individualEntityInvestor.mailingStreet1) &&
        Objects.equals(this.mailingStreet2, individualEntityInvestor.mailingStreet2) &&
        Objects.equals(this.mailingAddressAptSuiteNo, individualEntityInvestor.mailingAddressAptSuiteNo) &&
        Objects.equals(this.mailingAddressCity, individualEntityInvestor.mailingAddressCity) &&
        Objects.equals(this.mailingAddressState, individualEntityInvestor.mailingAddressState) &&
        Objects.equals(this.mailingAddressZipCode, individualEntityInvestor.mailingAddressZipCode) &&
        Objects.equals(this.mailingAddressCountry, individualEntityInvestor.mailingAddressCountry) &&
        Objects.equals(this.hasBackupWithholding, individualEntityInvestor.hasBackupWithholding) &&
        Objects.equals(this.exemptPayeeCode, individualEntityInvestor.exemptPayeeCode) &&
        Objects.equals(this.isSubscriptionAdvisorOrERA, individualEntityInvestor.isSubscriptionAdvisorOrERA) &&
        Objects.equals(this.email, individualEntityInvestor.email) &&
        Objects.equals(this.taxId, individualEntityInvestor.taxId) &&
        Objects.equals(this.passportNumber, individualEntityInvestor.passportNumber) &&
        Objects.equals(this.citizenship, individualEntityInvestor.citizenship) &&
        Objects.equals(this.qualifiedStatus, individualEntityInvestor.qualifiedStatus) &&
        Objects.equals(this.entityInvestorType, individualEntityInvestor.entityInvestorType) &&
        Objects.equals(this.percentageOwned, individualEntityInvestor.percentageOwned) &&
        Objects.equals(this.id, individualEntityInvestor.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, isUSBased, dateOfBirth, street1, street2, city, state, zipCode, countryCode, phoneCountryCode, phoneNumber, mailingStreet1, mailingStreet2, mailingAddressAptSuiteNo, mailingAddressCity, mailingAddressState, mailingAddressZipCode, mailingAddressCountry, hasBackupWithholding, exemptPayeeCode, isSubscriptionAdvisorOrERA, email, taxId, passportNumber, citizenship, qualifiedStatus, entityInvestorType, percentageOwned, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualEntityInvestor {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    isUSBased: ").append(toIndentedString(isUSBased)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    street1: ").append(toIndentedString(street1)).append("\n");
    sb.append("    street2: ").append(toIndentedString(street2)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    phoneCountryCode: ").append(toIndentedString(phoneCountryCode)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    mailingStreet1: ").append(toIndentedString(mailingStreet1)).append("\n");
    sb.append("    mailingStreet2: ").append(toIndentedString(mailingStreet2)).append("\n");
    sb.append("    mailingAddressAptSuiteNo: ").append(toIndentedString(mailingAddressAptSuiteNo)).append("\n");
    sb.append("    mailingAddressCity: ").append(toIndentedString(mailingAddressCity)).append("\n");
    sb.append("    mailingAddressState: ").append(toIndentedString(mailingAddressState)).append("\n");
    sb.append("    mailingAddressZipCode: ").append(toIndentedString(mailingAddressZipCode)).append("\n");
    sb.append("    mailingAddressCountry: ").append(toIndentedString(mailingAddressCountry)).append("\n");
    sb.append("    hasBackupWithholding: ").append(toIndentedString(hasBackupWithholding)).append("\n");
    sb.append("    exemptPayeeCode: ").append(toIndentedString(exemptPayeeCode)).append("\n");
    sb.append("    isSubscriptionAdvisorOrERA: ").append(toIndentedString(isSubscriptionAdvisorOrERA)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    taxId: ").append(toIndentedString(taxId)).append("\n");
    sb.append("    passportNumber: ").append(toIndentedString(passportNumber)).append("\n");
    sb.append("    citizenship: ").append(toIndentedString(citizenship)).append("\n");
    sb.append("    qualifiedStatus: ").append(toIndentedString(qualifiedStatus)).append("\n");
    sb.append("    entityInvestorType: ").append(toIndentedString(entityInvestorType)).append("\n");
    sb.append("    percentageOwned: ").append(toIndentedString(percentageOwned)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      try {
        joiner.add(String.format("%sfirstName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFirstName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      try {
        joiner.add(String.format("%slastName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isUSBased` to the URL query string
    if (getIsUSBased() != null) {
      try {
        joiner.add(String.format("%sisUSBased%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsUSBased()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `dateOfBirth` to the URL query string
    if (getDateOfBirth() != null) {
      try {
        joiner.add(String.format("%sdateOfBirth%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDateOfBirth()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `street1` to the URL query string
    if (getStreet1() != null) {
      try {
        joiner.add(String.format("%sstreet1%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStreet1()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `street2` to the URL query string
    if (getStreet2() != null) {
      try {
        joiner.add(String.format("%sstreet2%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStreet2()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `city` to the URL query string
    if (getCity() != null) {
      try {
        joiner.add(String.format("%scity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      try {
        joiner.add(String.format("%sstate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `zipCode` to the URL query string
    if (getZipCode() != null) {
      try {
        joiner.add(String.format("%szipCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getZipCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `countryCode` to the URL query string
    if (getCountryCode() != null) {
      try {
        joiner.add(String.format("%scountryCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCountryCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `phoneCountryCode` to the URL query string
    if (getPhoneCountryCode() != null) {
      try {
        joiner.add(String.format("%sphoneCountryCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPhoneCountryCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `phoneNumber` to the URL query string
    if (getPhoneNumber() != null) {
      try {
        joiner.add(String.format("%sphoneNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPhoneNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingStreet1` to the URL query string
    if (getMailingStreet1() != null) {
      try {
        joiner.add(String.format("%smailingStreet1%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingStreet1()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingStreet2` to the URL query string
    if (getMailingStreet2() != null) {
      try {
        joiner.add(String.format("%smailingStreet2%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingStreet2()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingAddressAptSuiteNo` to the URL query string
    if (getMailingAddressAptSuiteNo() != null) {
      try {
        joiner.add(String.format("%smailingAddressAptSuiteNo%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingAddressAptSuiteNo()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingAddressCity` to the URL query string
    if (getMailingAddressCity() != null) {
      try {
        joiner.add(String.format("%smailingAddressCity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingAddressCity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingAddressState` to the URL query string
    if (getMailingAddressState() != null) {
      try {
        joiner.add(String.format("%smailingAddressState%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingAddressState()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingAddressZipCode` to the URL query string
    if (getMailingAddressZipCode() != null) {
      try {
        joiner.add(String.format("%smailingAddressZipCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingAddressZipCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mailingAddressCountry` to the URL query string
    if (getMailingAddressCountry() != null) {
      try {
        joiner.add(String.format("%smailingAddressCountry%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMailingAddressCountry()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `hasBackupWithholding` to the URL query string
    if (getHasBackupWithholding() != null) {
      try {
        joiner.add(String.format("%shasBackupWithholding%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHasBackupWithholding()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `exemptPayeeCode` to the URL query string
    if (getExemptPayeeCode() != null) {
      try {
        joiner.add(String.format("%sexemptPayeeCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExemptPayeeCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `isSubscriptionAdvisorOrERA` to the URL query string
    if (getIsSubscriptionAdvisorOrERA() != null) {
      try {
        joiner.add(String.format("%sisSubscriptionAdvisorOrERA%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIsSubscriptionAdvisorOrERA()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      try {
        joiner.add(String.format("%semail%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEmail()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `taxId` to the URL query string
    if (getTaxId() != null) {
      try {
        joiner.add(String.format("%staxId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTaxId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `passportNumber` to the URL query string
    if (getPassportNumber() != null) {
      try {
        joiner.add(String.format("%spassportNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPassportNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `citizenship` to the URL query string
    if (getCitizenship() != null) {
      try {
        joiner.add(String.format("%scitizenship%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCitizenship()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `qualifiedStatus` to the URL query string
    if (getQualifiedStatus() != null) {
      try {
        joiner.add(String.format("%squalifiedStatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQualifiedStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `entityInvestorType` to the URL query string
    if (getEntityInvestorType() != null) {
      try {
        joiner.add(String.format("%sentityInvestorType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEntityInvestorType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `percentageOwned` to the URL query string
    if (getPercentageOwned() != null) {
      try {
        joiner.add(String.format("%spercentageOwned%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPercentageOwned()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

