/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;
import java.util.StringJoiner;

/**
 * InvestorPii
 */
@JsonPropertyOrder({
  InvestorPii.JSON_PROPERTY_INDIVIDUAL_INVESTOR,
  InvestorPii.JSON_PROPERTY_ENTITY_INVESTOR
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class InvestorPii {
  public static final String JSON_PROPERTY_INDIVIDUAL_INVESTOR = "individualInvestor";
  @jakarta.annotation.Nullable
  private ModifyIndividualInvestor individualInvestor;

  public static final String JSON_PROPERTY_ENTITY_INVESTOR = "entityInvestor";
  @jakarta.annotation.Nullable
  private UpdateEntityInvestor entityInvestor;

  public InvestorPii() {
  }

  public InvestorPii individualInvestor(@jakarta.annotation.Nullable ModifyIndividualInvestor individualInvestor) {
    
    this.individualInvestor = individualInvestor;
    return this;
  }

  /**
   * Information about the individual investor if this Investor is of that type.
   * @return individualInvestor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModifyIndividualInvestor getIndividualInvestor() {
    return individualInvestor;
  }


  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndividualInvestor(@jakarta.annotation.Nullable ModifyIndividualInvestor individualInvestor) {
    this.individualInvestor = individualInvestor;
  }

  public InvestorPii entityInvestor(@jakarta.annotation.Nullable UpdateEntityInvestor entityInvestor) {
    
    this.entityInvestor = entityInvestor;
    return this;
  }

  /**
   * Information about the entity investor if this Investor is of that type.
   * @return entityInvestor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateEntityInvestor getEntityInvestor() {
    return entityInvestor;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityInvestor(@jakarta.annotation.Nullable UpdateEntityInvestor entityInvestor) {
    this.entityInvestor = entityInvestor;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestorPii investorPii = (InvestorPii) o;
    return Objects.equals(this.individualInvestor, investorPii.individualInvestor) &&
        Objects.equals(this.entityInvestor, investorPii.entityInvestor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individualInvestor, entityInvestor);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestorPii {\n");
    sb.append("    individualInvestor: ").append(toIndentedString(individualInvestor)).append("\n");
    sb.append("    entityInvestor: ").append(toIndentedString(entityInvestor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `individualInvestor` to the URL query string
    if (getIndividualInvestor() != null) {
      joiner.add(getIndividualInvestor().toUrlQueryString(prefix + "individualInvestor" + suffix));
    }

    // add `entityInvestor` to the URL query string
    if (getEntityInvestor() != null) {
      joiner.add(getEntityInvestor().toUrlQueryString(prefix + "entityInvestor" + suffix));
    }

    return joiner.toString();
  }

}

