/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * InvestorSubscriptionAction
 */
@JsonPropertyOrder({
  InvestorSubscriptionAction.JSON_PROPERTY_ID,
  InvestorSubscriptionAction.JSON_PROPERTY_INVESTOR_SUBSCRIPTION_ID,
  InvestorSubscriptionAction.JSON_PROPERTY_NAME,
  InvestorSubscriptionAction.JSON_PROPERTY_DESCRIPTION,
  InvestorSubscriptionAction.JSON_PROPERTY_DATA_ID,
  InvestorSubscriptionAction.JSON_PROPERTY_STATUS,
  InvestorSubscriptionAction.JSON_PROPERTY_TYPE,
  InvestorSubscriptionAction.JSON_PROPERTY_RESPONSIBLE_PARTY,
  InvestorSubscriptionAction.JSON_PROPERTY_ACTION_TEXT
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class InvestorSubscriptionAction {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_INVESTOR_SUBSCRIPTION_ID = "investorSubscriptionId";
  @jakarta.annotation.Nullable
  private UUID investorSubscriptionId;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_DATA_ID = "dataId";
  @jakarta.annotation.Nullable
  private String dataId;

  /**
   * The current status of this InvestorSubscriptionAction.
   */
  public enum StatusEnum {
    PENDING(String.valueOf("Pending")),
    
    COMPLETE(String.valueOf("Complete"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nonnull
  private StatusEnum status;

  /**
   * The type of action required to be performed by the Investor, as part of executing the Subscription. DocumentSign and DocumentAcknowledge can both be completed by “signing” the associated document. InvestorSubscriptionActions with a type of DocumentSign mean that the associated document, once signed, will be populated with an automatically generated signature. InvestorSubscriptionActions with a type of DocumentAcknowledge mean that the associated document, once signed, will be counted as acknowledged but are not required to be populated by a signature.
   */
  public enum TypeEnum {
    OTHER(String.valueOf("Other")),
    
    DOCUMENT_SIGN(String.valueOf("DocumentSign")),
    
    DOCUMENT_ACKNOWLEDGE(String.valueOf("DocumentAcknowledge")),
    
    CASH_MOVEMENT(String.valueOf("CashMovement")),
    
    API_CALL(String.valueOf("ApiCall")),
    
    TEXT_ACKNOWLEDGE(String.valueOf("TextAcknowledge")),
    
    KYCAML(String.valueOf("KYCAML"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_TYPE = "type";
  @jakarta.annotation.Nonnull
  private TypeEnum type;

  /**
   * This describes the entity responsible for acknowledging that the Action has been completed. Partners acknowledge that actions have been completed on behalf of their Investors.
   */
  public enum ResponsiblePartyEnum {
    PARTNER(String.valueOf("Partner")),
    
    MONARK(String.valueOf("Monark"));

    private String value;

    ResponsiblePartyEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ResponsiblePartyEnum fromValue(String value) {
      for (ResponsiblePartyEnum b : ResponsiblePartyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESPONSIBLE_PARTY = "responsibleParty";
  @jakarta.annotation.Nonnull
  private ResponsiblePartyEnum responsibleParty;

  public static final String JSON_PROPERTY_ACTION_TEXT = "actionText";
  @jakarta.annotation.Nullable
  private String actionText;

  public InvestorSubscriptionAction() {
  }

  public InvestorSubscriptionAction id(@jakarta.annotation.Nullable UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID associated with an InvestorSubscriptionAction.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }

  public InvestorSubscriptionAction investorSubscriptionId(@jakarta.annotation.Nullable UUID investorSubscriptionId) {
    
    this.investorSubscriptionId = investorSubscriptionId;
    return this;
  }

  /**
   * Investor SubscriptionId for the InvestorSubscriptionAction record.
   * @return investorSubscriptionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INVESTOR_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getInvestorSubscriptionId() {
    return investorSubscriptionId;
  }


  @JsonProperty(JSON_PROPERTY_INVESTOR_SUBSCRIPTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInvestorSubscriptionId(@jakarta.annotation.Nullable UUID investorSubscriptionId) {
    this.investorSubscriptionId = investorSubscriptionId;
  }

  public InvestorSubscriptionAction name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * The name of this InvestorSubscriptionAction.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public InvestorSubscriptionAction description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * A description for this action.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public InvestorSubscriptionAction dataId(@jakarta.annotation.Nullable String dataId) {
    
    this.dataId = dataId;
    return this;
  }

  /**
   * Optional DataId for related object.
   * @return dataId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDataId() {
    return dataId;
  }


  @JsonProperty(JSON_PROPERTY_DATA_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDataId(@jakarta.annotation.Nullable String dataId) {
    this.dataId = dataId;
  }

  public InvestorSubscriptionAction status(@jakarta.annotation.Nonnull StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * The current status of this InvestorSubscriptionAction.
   * @return status
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@jakarta.annotation.Nonnull StatusEnum status) {
    this.status = status;
  }

  public InvestorSubscriptionAction type(@jakarta.annotation.Nonnull TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * The type of action required to be performed by the Investor, as part of executing the Subscription. DocumentSign and DocumentAcknowledge can both be completed by “signing” the associated document. InvestorSubscriptionActions with a type of DocumentSign mean that the associated document, once signed, will be populated with an automatically generated signature. InvestorSubscriptionActions with a type of DocumentAcknowledge mean that the associated document, once signed, will be counted as acknowledged but are not required to be populated by a signature.
   * @return type
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public TypeEnum getType() {
    return type;
  }


  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@jakarta.annotation.Nonnull TypeEnum type) {
    this.type = type;
  }

  public InvestorSubscriptionAction responsibleParty(@jakarta.annotation.Nonnull ResponsiblePartyEnum responsibleParty) {
    
    this.responsibleParty = responsibleParty;
    return this;
  }

  /**
   * This describes the entity responsible for acknowledging that the Action has been completed. Partners acknowledge that actions have been completed on behalf of their Investors.
   * @return responsibleParty
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSIBLE_PARTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ResponsiblePartyEnum getResponsibleParty() {
    return responsibleParty;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSIBLE_PARTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponsibleParty(@jakarta.annotation.Nonnull ResponsiblePartyEnum responsibleParty) {
    this.responsibleParty = responsibleParty;
  }

  public InvestorSubscriptionAction actionText(@jakarta.annotation.Nullable String actionText) {
    
    this.actionText = actionText;
    return this;
  }

  /**
   * Text for an action that is a text acknowledgement.
   * @return actionText
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTION_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActionText() {
    return actionText;
  }


  @JsonProperty(JSON_PROPERTY_ACTION_TEXT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActionText(@jakarta.annotation.Nullable String actionText) {
    this.actionText = actionText;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvestorSubscriptionAction investorSubscriptionAction = (InvestorSubscriptionAction) o;
    return Objects.equals(this.id, investorSubscriptionAction.id) &&
        Objects.equals(this.investorSubscriptionId, investorSubscriptionAction.investorSubscriptionId) &&
        Objects.equals(this.name, investorSubscriptionAction.name) &&
        Objects.equals(this.description, investorSubscriptionAction.description) &&
        Objects.equals(this.dataId, investorSubscriptionAction.dataId) &&
        Objects.equals(this.status, investorSubscriptionAction.status) &&
        Objects.equals(this.type, investorSubscriptionAction.type) &&
        Objects.equals(this.responsibleParty, investorSubscriptionAction.responsibleParty) &&
        Objects.equals(this.actionText, investorSubscriptionAction.actionText);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, investorSubscriptionId, name, description, dataId, status, type, responsibleParty, actionText);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvestorSubscriptionAction {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    investorSubscriptionId: ").append(toIndentedString(investorSubscriptionId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    dataId: ").append(toIndentedString(dataId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    responsibleParty: ").append(toIndentedString(responsibleParty)).append("\n");
    sb.append("    actionText: ").append(toIndentedString(actionText)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `investorSubscriptionId` to the URL query string
    if (getInvestorSubscriptionId() != null) {
      try {
        joiner.add(String.format("%sinvestorSubscriptionId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInvestorSubscriptionId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `dataId` to the URL query string
    if (getDataId() != null) {
      try {
        joiner.add(String.format("%sdataId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDataId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `type` to the URL query string
    if (getType() != null) {
      try {
        joiner.add(String.format("%stype%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `responsibleParty` to the URL query string
    if (getResponsibleParty() != null) {
      try {
        joiner.add(String.format("%sresponsibleParty%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getResponsibleParty()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `actionText` to the URL query string
    if (getActionText() != null) {
      try {
        joiner.add(String.format("%sactionText%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getActionText()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

