/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Represents a transition of an SPV to a specific stage in its lifecycle.
 */
@JsonPropertyOrder({
  MonarkStageTransition.JSON_PROPERTY_STAGE,
  MonarkStageTransition.JSON_PROPERTY_TIMESTAMP,
  MonarkStageTransition.JSON_PROPERTY_CHANGED_BY,
  MonarkStageTransition.JSON_PROPERTY_NOTE
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class MonarkStageTransition {
  /**
   * The stage the SPV transitioned to.
   */
  public enum StageEnum {
    DRAFT(String.valueOf("DRAFT")),
    
    WAITING_MONARK_REVIEW(String.valueOf("WAITING_MONARK_REVIEW")),
    
    FUND_ADMIN_REVIEW(String.valueOf("FUND_ADMIN_REVIEW")),
    
    FUND_ADMIN_APPROVED(String.valueOf("FUND_ADMIN_APPROVED")),
    
    PRIMARY_FUNDRAISE(String.valueOf("PRIMARY_FUNDRAISE")),
    
    PRE_CLOSE_REVIEW(String.valueOf("PRE_CLOSE_REVIEW")),
    
    CLOSE_REQUESTED(String.valueOf("CLOSE_REQUESTED")),
    
    CLOSE_IN_PROCESS(String.valueOf("CLOSE_IN_PROCESS")),
    
    FUNDS_SENT_TO_TARGET(String.valueOf("FUNDS_SENT_TO_TARGET")),
    
    CLOSED(String.valueOf("CLOSED")),
    
    REGULATORY_HOLD_PERIOD(String.valueOf("REGULATORY_HOLD_PERIOD")),
    
    ACTIVELY_TRADING(String.valueOf("ACTIVELY_TRADING")),
    
    CLOSE_FAILED(String.valueOf("CLOSE_FAILED")),
    
    HALTED(String.valueOf("HALTED")),
    
    LIQUIDATION(String.valueOf("LIQUIDATION")),
    
    DISSOLVED(String.valueOf("DISSOLVED"));

    private String value;

    StageEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StageEnum fromValue(String value) {
      for (StageEnum b : StageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STAGE = "stage";
  @jakarta.annotation.Nullable
  private StageEnum stage;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  @jakarta.annotation.Nullable
  private OffsetDateTime timestamp;

  public static final String JSON_PROPERTY_CHANGED_BY = "changedBy";
  @jakarta.annotation.Nullable
  private String changedBy;

  public static final String JSON_PROPERTY_NOTE = "note";
  @jakarta.annotation.Nullable
  private String note;

  public MonarkStageTransition() {
  }

  public MonarkStageTransition stage(@jakarta.annotation.Nullable StageEnum stage) {
    
    this.stage = stage;
    return this;
  }

  /**
   * The stage the SPV transitioned to.
   * @return stage
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StageEnum getStage() {
    return stage;
  }


  @JsonProperty(JSON_PROPERTY_STAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStage(@jakarta.annotation.Nullable StageEnum stage) {
    this.stage = stage;
  }

  public MonarkStageTransition timestamp(@jakarta.annotation.Nullable OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

  /**
   * The UTC timestamp when the transition to this stage occurred.
   * @return timestamp
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimestamp(@jakarta.annotation.Nullable OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

  public MonarkStageTransition changedBy(@jakarta.annotation.Nullable String changedBy) {
    
    this.changedBy = changedBy;
    return this;
  }

  /**
   * Optional identifier of the user or system that triggered the transition.
   * @return changedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChangedBy() {
    return changedBy;
  }


  @JsonProperty(JSON_PROPERTY_CHANGED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChangedBy(@jakarta.annotation.Nullable String changedBy) {
    this.changedBy = changedBy;
  }

  public MonarkStageTransition note(@jakarta.annotation.Nullable String note) {
    
    this.note = note;
    return this;
  }

  /**
   * Optional note or reason associated with the stage transition.
   * @return note
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNote() {
    return note;
  }


  @JsonProperty(JSON_PROPERTY_NOTE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNote(@jakarta.annotation.Nullable String note) {
    this.note = note;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonarkStageTransition monarkStageTransition = (MonarkStageTransition) o;
    return Objects.equals(this.stage, monarkStageTransition.stage) &&
        Objects.equals(this.timestamp, monarkStageTransition.timestamp) &&
        Objects.equals(this.changedBy, monarkStageTransition.changedBy) &&
        Objects.equals(this.note, monarkStageTransition.note);
  }

  @Override
  public int hashCode() {
    return Objects.hash(stage, timestamp, changedBy, note);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonarkStageTransition {\n");
    sb.append("    stage: ").append(toIndentedString(stage)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    changedBy: ").append(toIndentedString(changedBy)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `stage` to the URL query string
    if (getStage() != null) {
      try {
        joiner.add(String.format("%sstage%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStage()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `timestamp` to the URL query string
    if (getTimestamp() != null) {
      try {
        joiner.add(String.format("%stimestamp%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTimestamp()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `changedBy` to the URL query string
    if (getChangedBy() != null) {
      try {
        joiner.add(String.format("%schangedBy%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getChangedBy()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `note` to the URL query string
    if (getNote() != null) {
      try {
        joiner.add(String.format("%snote%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNote()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

