/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDate;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Represents a NAV (Net Asset Value) report for a share class.
 */
@JsonPropertyOrder({
  NAVReport.JSON_PROPERTY_ID,
  NAVReport.JSON_PROPERTY_SHARE_CLASS_ID,
  NAVReport.JSON_PROPERTY_REPORT_DATE,
  NAVReport.JSON_PROPERTY_NAV
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class NAVReport {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_SHARE_CLASS_ID = "shareClassId";
  @jakarta.annotation.Nonnull
  private UUID shareClassId;

  public static final String JSON_PROPERTY_REPORT_DATE = "reportDate";
  @jakarta.annotation.Nonnull
  private LocalDate reportDate;

  public static final String JSON_PROPERTY_NAV = "nav";
  @jakarta.annotation.Nonnull
  private Double nav;

  public NAVReport() {
  }

  public NAVReport id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID associated with this NAV report
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public NAVReport shareClassId(@jakarta.annotation.Nonnull UUID shareClassId) {
    
    this.shareClassId = shareClassId;
    return this;
  }

  /**
   * The ID of the class of shares associated with this NAV report
   * @return shareClassId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHARE_CLASS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getShareClassId() {
    return shareClassId;
  }


  @JsonProperty(JSON_PROPERTY_SHARE_CLASS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShareClassId(@jakarta.annotation.Nonnull UUID shareClassId) {
    this.shareClassId = shareClassId;
  }

  public NAVReport reportDate(@jakarta.annotation.Nonnull LocalDate reportDate) {
    
    this.reportDate = reportDate;
    return this;
  }

  /**
   * The date of this NAV report
   * @return reportDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REPORT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getReportDate() {
    return reportDate;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReportDate(@jakarta.annotation.Nonnull LocalDate reportDate) {
    this.reportDate = reportDate;
  }

  public NAVReport nav(@jakarta.annotation.Nonnull Double nav) {
    
    this.nav = nav;
    return this;
  }

  /**
   * Net Asset Value as of the reported date
   * @return nav
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAV)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getNav() {
    return nav;
  }


  @JsonProperty(JSON_PROPERTY_NAV)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNav(@jakarta.annotation.Nonnull Double nav) {
    this.nav = nav;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NAVReport naVReport = (NAVReport) o;
    return Objects.equals(this.id, naVReport.id) &&
        Objects.equals(this.shareClassId, naVReport.shareClassId) &&
        Objects.equals(this.reportDate, naVReport.reportDate) &&
        Objects.equals(this.nav, naVReport.nav);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, shareClassId, reportDate, nav);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NAVReport {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    shareClassId: ").append(toIndentedString(shareClassId)).append("\n");
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    nav: ").append(toIndentedString(nav)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shareClassId` to the URL query string
    if (getShareClassId() != null) {
      try {
        joiner.add(String.format("%sshareClassId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShareClassId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `reportDate` to the URL query string
    if (getReportDate() != null) {
      try {
        joiner.add(String.format("%sreportDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getReportDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `nav` to the URL query string
    if (getNav() != null) {
      try {
        joiner.add(String.format("%snav%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNav()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

