/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDate;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Represents an NPM Last Round (Funding Round) record (NPM/LRND).
 */
@JsonPropertyOrder({
  NpmFundingRound.JSON_PROPERTY_ID,
  NpmFundingRound.JSON_PROPERTY_PRE_I_P_O_COMPANY_ID,
  NpmFundingRound.JSON_PROPERTY_COMPANY_NAME,
  NpmFundingRound.JSON_PROPERTY_NPM_TICKER,
  NpmFundingRound.JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION,
  NpmFundingRound.JSON_PROPERTY_PRICE_PER_SHARE,
  NpmFundingRound.JSON_PROPERTY_LAST_ROUND_VALUATION,
  NpmFundingRound.JSON_PROPERTY_LAST_ROUND_NAME
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class NpmFundingRound {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PRE_I_P_O_COMPANY_ID = "preIPOCompanyId";
  @jakarta.annotation.Nonnull
  private UUID preIPOCompanyId;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  @jakarta.annotation.Nullable
  private String companyName;

  public static final String JSON_PROPERTY_NPM_TICKER = "npmTicker";
  @jakarta.annotation.Nullable
  private String npmTicker;

  public static final String JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION = "lastRoundDateOfValuation";
  @jakarta.annotation.Nonnull
  private LocalDate lastRoundDateOfValuation;

  public static final String JSON_PROPERTY_PRICE_PER_SHARE = "pricePerShare";
  @jakarta.annotation.Nullable
  private Double pricePerShare;

  public static final String JSON_PROPERTY_LAST_ROUND_VALUATION = "lastRoundValuation";
  @jakarta.annotation.Nullable
  private Double lastRoundValuation;

  public static final String JSON_PROPERTY_LAST_ROUND_NAME = "lastRoundName";
  @jakarta.annotation.Nullable
  private String lastRoundName;

  public NpmFundingRound() {
  }

  public NpmFundingRound id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique identifier for the NPM Last Round record.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public NpmFundingRound preIPOCompanyId(@jakarta.annotation.Nonnull UUID preIPOCompanyId) {
    
    this.preIPOCompanyId = preIPOCompanyId;
    return this;
  }

  /**
   * The unique ID of the PreIPOCompany associated with the Last Round record.
   * @return preIPOCompanyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getPreIPOCompanyId() {
    return preIPOCompanyId;
  }


  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreIPOCompanyId(@jakarta.annotation.Nonnull UUID preIPOCompanyId) {
    this.preIPOCompanyId = preIPOCompanyId;
  }

  public NpmFundingRound companyName(@jakarta.annotation.Nullable String companyName) {
    
    this.companyName = companyName;
    return this;
  }

  /**
   * Name of the Company.
   * @return companyName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyName(@jakarta.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }

  public NpmFundingRound npmTicker(@jakarta.annotation.Nullable String npmTicker) {
    
    this.npmTicker = npmTicker;
    return this;
  }

  /**
   * Unique Company ID (NPM Ticker).
   * @return npmTicker
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NPM_TICKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNpmTicker() {
    return npmTicker;
  }


  @JsonProperty(JSON_PROPERTY_NPM_TICKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNpmTicker(@jakarta.annotation.Nullable String npmTicker) {
    this.npmTicker = npmTicker;
  }

  public NpmFundingRound lastRoundDateOfValuation(@jakarta.annotation.Nonnull LocalDate lastRoundDateOfValuation) {
    
    this.lastRoundDateOfValuation = lastRoundDateOfValuation;
    return this;
  }

  /**
   * Date of the last round valuation (YYYY-MM-DD).
   * @return lastRoundDateOfValuation
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getLastRoundDateOfValuation() {
    return lastRoundDateOfValuation;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastRoundDateOfValuation(@jakarta.annotation.Nonnull LocalDate lastRoundDateOfValuation) {
    this.lastRoundDateOfValuation = lastRoundDateOfValuation;
  }

  public NpmFundingRound pricePerShare(@jakarta.annotation.Nullable Double pricePerShare) {
    
    this.pricePerShare = pricePerShare;
    return this;
  }

  /**
   * Price Per Share at the last round.
   * @return pricePerShare
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPricePerShare() {
    return pricePerShare;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricePerShare(@jakarta.annotation.Nullable Double pricePerShare) {
    this.pricePerShare = pricePerShare;
  }

  public NpmFundingRound lastRoundValuation(@jakarta.annotation.Nullable Double lastRoundValuation) {
    
    this.lastRoundValuation = lastRoundValuation;
    return this;
  }

  /**
   * Post-Money Valuation at the last round.
   * @return lastRoundValuation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLastRoundValuation() {
    return lastRoundValuation;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundValuation(@jakarta.annotation.Nullable Double lastRoundValuation) {
    this.lastRoundValuation = lastRoundValuation;
  }

  public NpmFundingRound lastRoundName(@jakarta.annotation.Nullable String lastRoundName) {
    
    this.lastRoundName = lastRoundName;
    return this;
  }

  /**
   * Name of the financing round.
   * @return lastRoundName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastRoundName() {
    return lastRoundName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundName(@jakarta.annotation.Nullable String lastRoundName) {
    this.lastRoundName = lastRoundName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NpmFundingRound npmFundingRound = (NpmFundingRound) o;
    return Objects.equals(this.id, npmFundingRound.id) &&
        Objects.equals(this.preIPOCompanyId, npmFundingRound.preIPOCompanyId) &&
        Objects.equals(this.companyName, npmFundingRound.companyName) &&
        Objects.equals(this.npmTicker, npmFundingRound.npmTicker) &&
        Objects.equals(this.lastRoundDateOfValuation, npmFundingRound.lastRoundDateOfValuation) &&
        Objects.equals(this.pricePerShare, npmFundingRound.pricePerShare) &&
        Objects.equals(this.lastRoundValuation, npmFundingRound.lastRoundValuation) &&
        Objects.equals(this.lastRoundName, npmFundingRound.lastRoundName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, preIPOCompanyId, companyName, npmTicker, lastRoundDateOfValuation, pricePerShare, lastRoundValuation, lastRoundName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NpmFundingRound {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    preIPOCompanyId: ").append(toIndentedString(preIPOCompanyId)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    npmTicker: ").append(toIndentedString(npmTicker)).append("\n");
    sb.append("    lastRoundDateOfValuation: ").append(toIndentedString(lastRoundDateOfValuation)).append("\n");
    sb.append("    pricePerShare: ").append(toIndentedString(pricePerShare)).append("\n");
    sb.append("    lastRoundValuation: ").append(toIndentedString(lastRoundValuation)).append("\n");
    sb.append("    lastRoundName: ").append(toIndentedString(lastRoundName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `preIPOCompanyId` to the URL query string
    if (getPreIPOCompanyId() != null) {
      try {
        joiner.add(String.format("%spreIPOCompanyId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPreIPOCompanyId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `companyName` to the URL query string
    if (getCompanyName() != null) {
      try {
        joiner.add(String.format("%scompanyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCompanyName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `npmTicker` to the URL query string
    if (getNpmTicker() != null) {
      try {
        joiner.add(String.format("%snpmTicker%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNpmTicker()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundDateOfValuation` to the URL query string
    if (getLastRoundDateOfValuation() != null) {
      try {
        joiner.add(String.format("%slastRoundDateOfValuation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundDateOfValuation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pricePerShare` to the URL query string
    if (getPricePerShare() != null) {
      try {
        joiner.add(String.format("%spricePerShare%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPricePerShare()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundValuation` to the URL query string
    if (getLastRoundValuation() != null) {
      try {
        joiner.add(String.format("%slastRoundValuation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundValuation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundName` to the URL query string
    if (getLastRoundName() != null) {
      try {
        joiner.add(String.format("%slastRoundName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

