/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDate;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Represents an NPM mutual fund mark (NPM/MFM).
 */
@JsonPropertyOrder({
  NpmMutualFundMark.JSON_PROPERTY_ID,
  NpmMutualFundMark.JSON_PROPERTY_PRE_I_P_O_COMPANY_ID,
  NpmMutualFundMark.JSON_PROPERTY_RECORD_ID,
  NpmMutualFundMark.JSON_PROPERTY_COMPANY_NAME,
  NpmMutualFundMark.JSON_PROPERTY_NPM_TICKER,
  NpmMutualFundMark.JSON_PROPERTY_PARENT_ENTITY,
  NpmMutualFundMark.JSON_PROPERTY_MUTUAL_FUND_NAME,
  NpmMutualFundMark.JSON_PROPERTY_ASSET_TYPE,
  NpmMutualFundMark.JSON_PROPERTY_FILING_DATE,
  NpmMutualFundMark.JSON_PROPERTY_REPORTING_PERIOD,
  NpmMutualFundMark.JSON_PROPERTY_PRICE_PER_SHARE,
  NpmMutualFundMark.JSON_PROPERTY_PREMIUM_OR_DISCOUNT,
  NpmMutualFundMark.JSON_PROPERTY_IMPLIED_VALUATION,
  NpmMutualFundMark.JSON_PROPERTY_LAST_ROUND_NAME,
  NpmMutualFundMark.JSON_PROPERTY_LAST_ROUND_PRICE_PER_SHARE,
  NpmMutualFundMark.JSON_PROPERTY_LAST_ROUND_VALUATION,
  NpmMutualFundMark.JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class NpmMutualFundMark {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_PRE_I_P_O_COMPANY_ID = "preIPOCompanyId";
  @jakarta.annotation.Nonnull
  private UUID preIPOCompanyId;

  public static final String JSON_PROPERTY_RECORD_ID = "recordId";
  @jakarta.annotation.Nonnull
  private Integer recordId;

  public static final String JSON_PROPERTY_COMPANY_NAME = "companyName";
  @jakarta.annotation.Nullable
  private String companyName;

  public static final String JSON_PROPERTY_NPM_TICKER = "npmTicker";
  @jakarta.annotation.Nullable
  private String npmTicker;

  public static final String JSON_PROPERTY_PARENT_ENTITY = "parentEntity";
  @jakarta.annotation.Nullable
  private String parentEntity;

  public static final String JSON_PROPERTY_MUTUAL_FUND_NAME = "mutualFundName";
  @jakarta.annotation.Nullable
  private String mutualFundName;

  public static final String JSON_PROPERTY_ASSET_TYPE = "assetType";
  @jakarta.annotation.Nullable
  private String assetType;

  public static final String JSON_PROPERTY_FILING_DATE = "filingDate";
  @jakarta.annotation.Nonnull
  private LocalDate filingDate;

  public static final String JSON_PROPERTY_REPORTING_PERIOD = "reportingPeriod";
  @jakarta.annotation.Nullable
  private LocalDate reportingPeriod;

  public static final String JSON_PROPERTY_PRICE_PER_SHARE = "pricePerShare";
  @jakarta.annotation.Nullable
  private String pricePerShare;

  public static final String JSON_PROPERTY_PREMIUM_OR_DISCOUNT = "premiumOrDiscount";
  @jakarta.annotation.Nullable
  private Double premiumOrDiscount;

  public static final String JSON_PROPERTY_IMPLIED_VALUATION = "impliedValuation";
  @jakarta.annotation.Nullable
  private Double impliedValuation;

  public static final String JSON_PROPERTY_LAST_ROUND_NAME = "lastRoundName";
  @jakarta.annotation.Nullable
  private String lastRoundName;

  public static final String JSON_PROPERTY_LAST_ROUND_PRICE_PER_SHARE = "lastRoundPricePerShare";
  @jakarta.annotation.Nullable
  private Double lastRoundPricePerShare;

  public static final String JSON_PROPERTY_LAST_ROUND_VALUATION = "lastRoundValuation";
  @jakarta.annotation.Nullable
  private Double lastRoundValuation;

  public static final String JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION = "lastRoundDateOfValuation";
  @jakarta.annotation.Nullable
  private LocalDate lastRoundDateOfValuation;

  public NpmMutualFundMark() {
  }

  public NpmMutualFundMark id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique identification number for NPM mutual fund mark.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public NpmMutualFundMark preIPOCompanyId(@jakarta.annotation.Nonnull UUID preIPOCompanyId) {
    
    this.preIPOCompanyId = preIPOCompanyId;
    return this;
  }

  /**
   * The unique ID of the PreIPOCompany associated with an NPM mutual fund mark.
   * @return preIPOCompanyId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getPreIPOCompanyId() {
    return preIPOCompanyId;
  }


  @JsonProperty(JSON_PROPERTY_PRE_I_P_O_COMPANY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPreIPOCompanyId(@jakarta.annotation.Nonnull UUID preIPOCompanyId) {
    this.preIPOCompanyId = preIPOCompanyId;
  }

  public NpmMutualFundMark recordId(@jakarta.annotation.Nonnull Integer recordId) {
    
    this.recordId = recordId;
    return this;
  }

  /**
   * Unique NPM mutual fund mark ID.
   * @return recordId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RECORD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRecordId() {
    return recordId;
  }


  @JsonProperty(JSON_PROPERTY_RECORD_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRecordId(@jakarta.annotation.Nonnull Integer recordId) {
    this.recordId = recordId;
  }

  public NpmMutualFundMark companyName(@jakarta.annotation.Nullable String companyName) {
    
    this.companyName = companyName;
    return this;
  }

  /**
   * Name of Company.
   * @return companyName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCompanyName() {
    return companyName;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompanyName(@jakarta.annotation.Nullable String companyName) {
    this.companyName = companyName;
  }

  public NpmMutualFundMark npmTicker(@jakarta.annotation.Nullable String npmTicker) {
    
    this.npmTicker = npmTicker;
    return this;
  }

  /**
   * NPM Ticker.
   * @return npmTicker
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NPM_TICKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNpmTicker() {
    return npmTicker;
  }


  @JsonProperty(JSON_PROPERTY_NPM_TICKER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNpmTicker(@jakarta.annotation.Nullable String npmTicker) {
    this.npmTicker = npmTicker;
  }

  public NpmMutualFundMark parentEntity(@jakarta.annotation.Nullable String parentEntity) {
    
    this.parentEntity = parentEntity;
    return this;
  }

  /**
   * Mutual Fund Parent Entity.
   * @return parentEntity
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARENT_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getParentEntity() {
    return parentEntity;
  }


  @JsonProperty(JSON_PROPERTY_PARENT_ENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentEntity(@jakarta.annotation.Nullable String parentEntity) {
    this.parentEntity = parentEntity;
  }

  public NpmMutualFundMark mutualFundName(@jakarta.annotation.Nullable String mutualFundName) {
    
    this.mutualFundName = mutualFundName;
    return this;
  }

  /**
   * Mutual Fund Series Name.
   * @return mutualFundName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MUTUAL_FUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMutualFundName() {
    return mutualFundName;
  }


  @JsonProperty(JSON_PROPERTY_MUTUAL_FUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMutualFundName(@jakarta.annotation.Nullable String mutualFundName) {
    this.mutualFundName = mutualFundName;
  }

  public NpmMutualFundMark assetType(@jakarta.annotation.Nullable String assetType) {
    
    this.assetType = assetType;
    return this;
  }

  /**
   * Type of Asset Owned by Fund.
   * @return assetType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetType() {
    return assetType;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetType(@jakarta.annotation.Nullable String assetType) {
    this.assetType = assetType;
  }

  public NpmMutualFundMark filingDate(@jakarta.annotation.Nonnull LocalDate filingDate) {
    
    this.filingDate = filingDate;
    return this;
  }

  /**
   * Date Mark was filed (YYYY-MM-DD).
   * @return filingDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LocalDate getFilingDate() {
    return filingDate;
  }


  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFilingDate(@jakarta.annotation.Nonnull LocalDate filingDate) {
    this.filingDate = filingDate;
  }

  public NpmMutualFundMark reportingPeriod(@jakarta.annotation.Nullable LocalDate reportingPeriod) {
    
    this.reportingPeriod = reportingPeriod;
    return this;
  }

  /**
   * Reporting Period of Mark (YYYY-MM-DD).
   * @return reportingPeriod
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORTING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getReportingPeriod() {
    return reportingPeriod;
  }


  @JsonProperty(JSON_PROPERTY_REPORTING_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportingPeriod(@jakarta.annotation.Nullable LocalDate reportingPeriod) {
    this.reportingPeriod = reportingPeriod;
  }

  public NpmMutualFundMark pricePerShare(@jakarta.annotation.Nullable String pricePerShare) {
    
    this.pricePerShare = pricePerShare;
    return this;
  }

  /**
   * Price Per Share.
   * @return pricePerShare
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPricePerShare() {
    return pricePerShare;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPricePerShare(@jakarta.annotation.Nullable String pricePerShare) {
    this.pricePerShare = pricePerShare;
  }

  public NpmMutualFundMark premiumOrDiscount(@jakarta.annotation.Nullable Double premiumOrDiscount) {
    
    this.premiumOrDiscount = premiumOrDiscount;
    return this;
  }

  /**
   * Premium or Discount in Price Per Share relative to last round of capital raise.
   * @return premiumOrDiscount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREMIUM_OR_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPremiumOrDiscount() {
    return premiumOrDiscount;
  }


  @JsonProperty(JSON_PROPERTY_PREMIUM_OR_DISCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPremiumOrDiscount(@jakarta.annotation.Nullable Double premiumOrDiscount) {
    this.premiumOrDiscount = premiumOrDiscount;
  }

  public NpmMutualFundMark impliedValuation(@jakarta.annotation.Nullable Double impliedValuation) {
    
    this.impliedValuation = impliedValuation;
    return this;
  }

  /**
   * Implied Valuation of Company.
   * @return impliedValuation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMPLIED_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getImpliedValuation() {
    return impliedValuation;
  }


  @JsonProperty(JSON_PROPERTY_IMPLIED_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImpliedValuation(@jakarta.annotation.Nullable Double impliedValuation) {
    this.impliedValuation = impliedValuation;
  }

  public NpmMutualFundMark lastRoundName(@jakarta.annotation.Nullable String lastRoundName) {
    
    this.lastRoundName = lastRoundName;
    return this;
  }

  /**
   * Name of Last Round.
   * @return lastRoundName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastRoundName() {
    return lastRoundName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundName(@jakarta.annotation.Nullable String lastRoundName) {
    this.lastRoundName = lastRoundName;
  }

  public NpmMutualFundMark lastRoundPricePerShare(@jakarta.annotation.Nullable Double lastRoundPricePerShare) {
    
    this.lastRoundPricePerShare = lastRoundPricePerShare;
    return this;
  }

  /**
   * Last Round Price Per Share.
   * @return lastRoundPricePerShare
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLastRoundPricePerShare() {
    return lastRoundPricePerShare;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_PRICE_PER_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundPricePerShare(@jakarta.annotation.Nullable Double lastRoundPricePerShare) {
    this.lastRoundPricePerShare = lastRoundPricePerShare;
  }

  public NpmMutualFundMark lastRoundValuation(@jakarta.annotation.Nullable Double lastRoundValuation) {
    
    this.lastRoundValuation = lastRoundValuation;
    return this;
  }

  /**
   * Valuation of Company as of Last Round.
   * @return lastRoundValuation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLastRoundValuation() {
    return lastRoundValuation;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundValuation(@jakarta.annotation.Nullable Double lastRoundValuation) {
    this.lastRoundValuation = lastRoundValuation;
  }

  public NpmMutualFundMark lastRoundDateOfValuation(@jakarta.annotation.Nullable LocalDate lastRoundDateOfValuation) {
    
    this.lastRoundDateOfValuation = lastRoundDateOfValuation;
    return this;
  }

  /**
   * Date of Last Round (YYYY-MM-DD).
   * @return lastRoundDateOfValuation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getLastRoundDateOfValuation() {
    return lastRoundDateOfValuation;
  }


  @JsonProperty(JSON_PROPERTY_LAST_ROUND_DATE_OF_VALUATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastRoundDateOfValuation(@jakarta.annotation.Nullable LocalDate lastRoundDateOfValuation) {
    this.lastRoundDateOfValuation = lastRoundDateOfValuation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NpmMutualFundMark npmMutualFundMark = (NpmMutualFundMark) o;
    return Objects.equals(this.id, npmMutualFundMark.id) &&
        Objects.equals(this.preIPOCompanyId, npmMutualFundMark.preIPOCompanyId) &&
        Objects.equals(this.recordId, npmMutualFundMark.recordId) &&
        Objects.equals(this.companyName, npmMutualFundMark.companyName) &&
        Objects.equals(this.npmTicker, npmMutualFundMark.npmTicker) &&
        Objects.equals(this.parentEntity, npmMutualFundMark.parentEntity) &&
        Objects.equals(this.mutualFundName, npmMutualFundMark.mutualFundName) &&
        Objects.equals(this.assetType, npmMutualFundMark.assetType) &&
        Objects.equals(this.filingDate, npmMutualFundMark.filingDate) &&
        Objects.equals(this.reportingPeriod, npmMutualFundMark.reportingPeriod) &&
        Objects.equals(this.pricePerShare, npmMutualFundMark.pricePerShare) &&
        Objects.equals(this.premiumOrDiscount, npmMutualFundMark.premiumOrDiscount) &&
        Objects.equals(this.impliedValuation, npmMutualFundMark.impliedValuation) &&
        Objects.equals(this.lastRoundName, npmMutualFundMark.lastRoundName) &&
        Objects.equals(this.lastRoundPricePerShare, npmMutualFundMark.lastRoundPricePerShare) &&
        Objects.equals(this.lastRoundValuation, npmMutualFundMark.lastRoundValuation) &&
        Objects.equals(this.lastRoundDateOfValuation, npmMutualFundMark.lastRoundDateOfValuation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, preIPOCompanyId, recordId, companyName, npmTicker, parentEntity, mutualFundName, assetType, filingDate, reportingPeriod, pricePerShare, premiumOrDiscount, impliedValuation, lastRoundName, lastRoundPricePerShare, lastRoundValuation, lastRoundDateOfValuation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NpmMutualFundMark {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    preIPOCompanyId: ").append(toIndentedString(preIPOCompanyId)).append("\n");
    sb.append("    recordId: ").append(toIndentedString(recordId)).append("\n");
    sb.append("    companyName: ").append(toIndentedString(companyName)).append("\n");
    sb.append("    npmTicker: ").append(toIndentedString(npmTicker)).append("\n");
    sb.append("    parentEntity: ").append(toIndentedString(parentEntity)).append("\n");
    sb.append("    mutualFundName: ").append(toIndentedString(mutualFundName)).append("\n");
    sb.append("    assetType: ").append(toIndentedString(assetType)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    reportingPeriod: ").append(toIndentedString(reportingPeriod)).append("\n");
    sb.append("    pricePerShare: ").append(toIndentedString(pricePerShare)).append("\n");
    sb.append("    premiumOrDiscount: ").append(toIndentedString(premiumOrDiscount)).append("\n");
    sb.append("    impliedValuation: ").append(toIndentedString(impliedValuation)).append("\n");
    sb.append("    lastRoundName: ").append(toIndentedString(lastRoundName)).append("\n");
    sb.append("    lastRoundPricePerShare: ").append(toIndentedString(lastRoundPricePerShare)).append("\n");
    sb.append("    lastRoundValuation: ").append(toIndentedString(lastRoundValuation)).append("\n");
    sb.append("    lastRoundDateOfValuation: ").append(toIndentedString(lastRoundDateOfValuation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `preIPOCompanyId` to the URL query string
    if (getPreIPOCompanyId() != null) {
      try {
        joiner.add(String.format("%spreIPOCompanyId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPreIPOCompanyId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `recordId` to the URL query string
    if (getRecordId() != null) {
      try {
        joiner.add(String.format("%srecordId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRecordId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `companyName` to the URL query string
    if (getCompanyName() != null) {
      try {
        joiner.add(String.format("%scompanyName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCompanyName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `npmTicker` to the URL query string
    if (getNpmTicker() != null) {
      try {
        joiner.add(String.format("%snpmTicker%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNpmTicker()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `parentEntity` to the URL query string
    if (getParentEntity() != null) {
      try {
        joiner.add(String.format("%sparentEntity%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getParentEntity()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `mutualFundName` to the URL query string
    if (getMutualFundName() != null) {
      try {
        joiner.add(String.format("%smutualFundName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMutualFundName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `assetType` to the URL query string
    if (getAssetType() != null) {
      try {
        joiner.add(String.format("%sassetType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAssetType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `filingDate` to the URL query string
    if (getFilingDate() != null) {
      try {
        joiner.add(String.format("%sfilingDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFilingDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `reportingPeriod` to the URL query string
    if (getReportingPeriod() != null) {
      try {
        joiner.add(String.format("%sreportingPeriod%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getReportingPeriod()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `pricePerShare` to the URL query string
    if (getPricePerShare() != null) {
      try {
        joiner.add(String.format("%spricePerShare%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPricePerShare()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `premiumOrDiscount` to the URL query string
    if (getPremiumOrDiscount() != null) {
      try {
        joiner.add(String.format("%spremiumOrDiscount%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPremiumOrDiscount()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `impliedValuation` to the URL query string
    if (getImpliedValuation() != null) {
      try {
        joiner.add(String.format("%simpliedValuation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getImpliedValuation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundName` to the URL query string
    if (getLastRoundName() != null) {
      try {
        joiner.add(String.format("%slastRoundName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundPricePerShare` to the URL query string
    if (getLastRoundPricePerShare() != null) {
      try {
        joiner.add(String.format("%slastRoundPricePerShare%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundPricePerShare()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundValuation` to the URL query string
    if (getLastRoundValuation() != null) {
      try {
        joiner.add(String.format("%slastRoundValuation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundValuation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lastRoundDateOfValuation` to the URL query string
    if (getLastRoundDateOfValuation() != null) {
      try {
        joiner.add(String.format("%slastRoundDateOfValuation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLastRoundDateOfValuation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

