/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Partner represents the primary offering information of the investor.
 */
@JsonPropertyOrder({
  Partner.JSON_PROPERTY_ID,
  Partner.JSON_PROPERTY_NAME,
  Partner.JSON_PROPERTY_PARTNER_TYPE,
  Partner.JSON_PROPERTY_LEGAL_ENTITY_NAME,
  Partner.JSON_PROPERTY_COUNTRY_CODE,
  Partner.JSON_PROPERTY_WEBSITE,
  Partner.JSON_PROPERTY_EXECUTIVE_TEAM,
  Partner.JSON_PROPERTY_DBA_NAME,
  Partner.JSON_PROPERTY_LOGO_URL,
  Partner.JSON_PROPERTY_FOUNDING_DATE,
  Partner.JSON_PROPERTY_AUM,
  Partner.JSON_PROPERTY_DESCRIPTION,
  Partner.JSON_PROPERTY_SECONDARY_LOCATION,
  Partner.JSON_PROPERTY_REGISTRATION,
  Partner.JSON_PROPERTY_MANAGER_C_R_D
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class Partner {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  /**
   * Type of the Partner.
   */
  public enum PartnerTypeEnum {
    BROKERAGE_FIRM(String.valueOf("BrokerageFirm")),
    
    THIRD_PARTY_MANAGER(String.valueOf("ThirdPartyManager"));

    private String value;

    PartnerTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static PartnerTypeEnum fromValue(String value) {
      for (PartnerTypeEnum b : PartnerTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PARTNER_TYPE = "partnerType";
  @jakarta.annotation.Nonnull
  private PartnerTypeEnum partnerType;

  public static final String JSON_PROPERTY_LEGAL_ENTITY_NAME = "legalEntityName";
  @jakarta.annotation.Nullable
  private String legalEntityName;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "countryCode";
  @jakarta.annotation.Nullable
  private String countryCode;

  public static final String JSON_PROPERTY_WEBSITE = "website";
  @jakarta.annotation.Nullable
  private String website;

  public static final String JSON_PROPERTY_EXECUTIVE_TEAM = "executiveTeam";
  @jakarta.annotation.Nullable
  private List<String> executiveTeam;

  public static final String JSON_PROPERTY_DBA_NAME = "dbaName";
  @jakarta.annotation.Nullable
  private String dbaName;

  public static final String JSON_PROPERTY_LOGO_URL = "logoUrl";
  @jakarta.annotation.Nullable
  private String logoUrl;

  public static final String JSON_PROPERTY_FOUNDING_DATE = "foundingDate";
  @jakarta.annotation.Nullable
  private LocalDate foundingDate;

  public static final String JSON_PROPERTY_AUM = "aum";
  @jakarta.annotation.Nullable
  private Double aum;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_SECONDARY_LOCATION = "secondaryLocation";
  @jakarta.annotation.Nullable
  private String secondaryLocation;

  /**
   * Registration or exemption.
   */
  public enum RegistrationEnum {
    OTHER(String.valueOf("OTHER")),
    
    BROKER_DEALER(String.valueOf("BROKER_DEALER")),
    
    EXEMPT_REPORTING_ADVISOR(String.valueOf("EXEMPT_REPORTING_ADVISOR")),
    
    RIA(String.valueOf("RIA"));

    private String value;

    RegistrationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RegistrationEnum fromValue(String value) {
      for (RegistrationEnum b : RegistrationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_REGISTRATION = "registration";
  @jakarta.annotation.Nullable
  private RegistrationEnum registration;

  public static final String JSON_PROPERTY_MANAGER_C_R_D = "managerCRD";
  @jakarta.annotation.Nullable
  private List<String> managerCRD;

  public Partner() {
  }

  public Partner id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID, provided by Monark, associated with a Partner.
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public Partner name(@jakarta.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name of the Partner.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }

  public Partner partnerType(@jakarta.annotation.Nonnull PartnerTypeEnum partnerType) {
    
    this.partnerType = partnerType;
    return this;
  }

  /**
   * Type of the Partner.
   * @return partnerType
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTNER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PartnerTypeEnum getPartnerType() {
    return partnerType;
  }


  @JsonProperty(JSON_PROPERTY_PARTNER_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPartnerType(@jakarta.annotation.Nonnull PartnerTypeEnum partnerType) {
    this.partnerType = partnerType;
  }

  public Partner legalEntityName(@jakarta.annotation.Nullable String legalEntityName) {
    
    this.legalEntityName = legalEntityName;
    return this;
  }

  /**
   * Legal Entity Name of the partner.
   * @return legalEntityName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLegalEntityName() {
    return legalEntityName;
  }


  @JsonProperty(JSON_PROPERTY_LEGAL_ENTITY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLegalEntityName(@jakarta.annotation.Nullable String legalEntityName) {
    this.legalEntityName = legalEntityName;
  }

  public Partner countryCode(@jakarta.annotation.Nullable String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

  /**
   * Country code of the investor.
   * @return countryCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCode(@jakarta.annotation.Nullable String countryCode) {
    this.countryCode = countryCode;
  }

  public Partner website(@jakarta.annotation.Nullable String website) {
    
    this.website = website;
    return this;
  }

  /**
   * Website of the Partner.
   * @return website
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWebsite() {
    return website;
  }


  @JsonProperty(JSON_PROPERTY_WEBSITE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebsite(@jakarta.annotation.Nullable String website) {
    this.website = website;
  }

  public Partner executiveTeam(@jakarta.annotation.Nullable List<String> executiveTeam) {
    
    this.executiveTeam = executiveTeam;
    return this;
  }

  public Partner addExecutiveTeamItem(String executiveTeamItem) {
    if (this.executiveTeam == null) {
      this.executiveTeam = new ArrayList<>();
    }
    this.executiveTeam.add(executiveTeamItem);
    return this;
  }

  /**
   * Executive Team of the partner.
   * @return executiveTeam
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXECUTIVE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getExecutiveTeam() {
    return executiveTeam;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTIVE_TEAM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutiveTeam(@jakarta.annotation.Nullable List<String> executiveTeam) {
    this.executiveTeam = executiveTeam;
  }

  public Partner dbaName(@jakarta.annotation.Nullable String dbaName) {
    
    this.dbaName = dbaName;
    return this;
  }

  /**
   * DBA name for the Partner.
   * @return dbaName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DBA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDbaName() {
    return dbaName;
  }


  @JsonProperty(JSON_PROPERTY_DBA_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDbaName(@jakarta.annotation.Nullable String dbaName) {
    this.dbaName = dbaName;
  }

  public Partner logoUrl(@jakarta.annotation.Nullable String logoUrl) {
    
    this.logoUrl = logoUrl;
    return this;
  }

  /**
   * Link to representative logo for management firm.
   * @return logoUrl
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogoUrl() {
    return logoUrl;
  }


  @JsonProperty(JSON_PROPERTY_LOGO_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogoUrl(@jakarta.annotation.Nullable String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public Partner foundingDate(@jakarta.annotation.Nullable LocalDate foundingDate) {
    
    this.foundingDate = foundingDate;
    return this;
  }

  /**
   * Year when management firm was first established.
   * @return foundingDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOUNDING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getFoundingDate() {
    return foundingDate;
  }


  @JsonProperty(JSON_PROPERTY_FOUNDING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFoundingDate(@jakarta.annotation.Nullable LocalDate foundingDate) {
    this.foundingDate = foundingDate;
  }

  public Partner aum(@jakarta.annotation.Nullable Double aum) {
    
    this.aum = aum;
    return this;
  }

  /**
   * Total AUM of manager.
   * @return aum
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAum() {
    return aum;
  }


  @JsonProperty(JSON_PROPERTY_AUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAum(@jakarta.annotation.Nullable Double aum) {
    this.aum = aum;
  }

  public Partner description(@jakarta.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Brief description of focus, history, and experience of management firm.
   * @return description
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@jakarta.annotation.Nullable String description) {
    this.description = description;
  }

  public Partner secondaryLocation(@jakarta.annotation.Nullable String secondaryLocation) {
    
    this.secondaryLocation = secondaryLocation;
    return this;
  }

  /**
   * Additional locations in which the Manager firm has permanent representation.
   * @return secondaryLocation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECONDARY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSecondaryLocation() {
    return secondaryLocation;
  }


  @JsonProperty(JSON_PROPERTY_SECONDARY_LOCATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSecondaryLocation(@jakarta.annotation.Nullable String secondaryLocation) {
    this.secondaryLocation = secondaryLocation;
  }

  public Partner registration(@jakarta.annotation.Nullable RegistrationEnum registration) {
    
    this.registration = registration;
    return this;
  }

  /**
   * Registration or exemption.
   * @return registration
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegistrationEnum getRegistration() {
    return registration;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistration(@jakarta.annotation.Nullable RegistrationEnum registration) {
    this.registration = registration;
  }

  public Partner managerCRD(@jakarta.annotation.Nullable List<String> managerCRD) {
    
    this.managerCRD = managerCRD;
    return this;
  }

  public Partner addManagerCRDItem(String managerCRDItem) {
    if (this.managerCRD == null) {
      this.managerCRD = new ArrayList<>();
    }
    this.managerCRD.add(managerCRDItem);
    return this;
  }

  /**
   * CRD number if manager firm is registered. If the Manager firm operated multiple registered / reporting entities, all CRD numbers can be listed here.
   * @return managerCRD
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MANAGER_C_R_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getManagerCRD() {
    return managerCRD;
  }


  @JsonProperty(JSON_PROPERTY_MANAGER_C_R_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManagerCRD(@jakarta.annotation.Nullable List<String> managerCRD) {
    this.managerCRD = managerCRD;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Partner partner = (Partner) o;
    return Objects.equals(this.id, partner.id) &&
        Objects.equals(this.name, partner.name) &&
        Objects.equals(this.partnerType, partner.partnerType) &&
        Objects.equals(this.legalEntityName, partner.legalEntityName) &&
        Objects.equals(this.countryCode, partner.countryCode) &&
        Objects.equals(this.website, partner.website) &&
        Objects.equals(this.executiveTeam, partner.executiveTeam) &&
        Objects.equals(this.dbaName, partner.dbaName) &&
        Objects.equals(this.logoUrl, partner.logoUrl) &&
        Objects.equals(this.foundingDate, partner.foundingDate) &&
        Objects.equals(this.aum, partner.aum) &&
        Objects.equals(this.description, partner.description) &&
        Objects.equals(this.secondaryLocation, partner.secondaryLocation) &&
        Objects.equals(this.registration, partner.registration) &&
        Objects.equals(this.managerCRD, partner.managerCRD);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, partnerType, legalEntityName, countryCode, website, executiveTeam, dbaName, logoUrl, foundingDate, aum, description, secondaryLocation, registration, managerCRD);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Partner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    partnerType: ").append(toIndentedString(partnerType)).append("\n");
    sb.append("    legalEntityName: ").append(toIndentedString(legalEntityName)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    executiveTeam: ").append(toIndentedString(executiveTeam)).append("\n");
    sb.append("    dbaName: ").append(toIndentedString(dbaName)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    foundingDate: ").append(toIndentedString(foundingDate)).append("\n");
    sb.append("    aum: ").append(toIndentedString(aum)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    secondaryLocation: ").append(toIndentedString(secondaryLocation)).append("\n");
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("    managerCRD: ").append(toIndentedString(managerCRD)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `partnerType` to the URL query string
    if (getPartnerType() != null) {
      try {
        joiner.add(String.format("%spartnerType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPartnerType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `legalEntityName` to the URL query string
    if (getLegalEntityName() != null) {
      try {
        joiner.add(String.format("%slegalEntityName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLegalEntityName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `countryCode` to the URL query string
    if (getCountryCode() != null) {
      try {
        joiner.add(String.format("%scountryCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCountryCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `website` to the URL query string
    if (getWebsite() != null) {
      try {
        joiner.add(String.format("%swebsite%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWebsite()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `executiveTeam` to the URL query string
    if (getExecutiveTeam() != null) {
      for (int i = 0; i < getExecutiveTeam().size(); i++) {
        try {
          joiner.add(String.format("%sexecutiveTeam%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getExecutiveTeam().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `dbaName` to the URL query string
    if (getDbaName() != null) {
      try {
        joiner.add(String.format("%sdbaName%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDbaName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `logoUrl` to the URL query string
    if (getLogoUrl() != null) {
      try {
        joiner.add(String.format("%slogoUrl%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLogoUrl()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `foundingDate` to the URL query string
    if (getFoundingDate() != null) {
      try {
        joiner.add(String.format("%sfoundingDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFoundingDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `aum` to the URL query string
    if (getAum() != null) {
      try {
        joiner.add(String.format("%saum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `secondaryLocation` to the URL query string
    if (getSecondaryLocation() != null) {
      try {
        joiner.add(String.format("%ssecondaryLocation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSecondaryLocation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `registration` to the URL query string
    if (getRegistration() != null) {
      try {
        joiner.add(String.format("%sregistration%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRegistration()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `managerCRD` to the URL query string
    if (getManagerCRD() != null) {
      for (int i = 0; i < getManagerCRD().size(); i++) {
        try {
          joiner.add(String.format("%smanagerCRD%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getManagerCRD().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    return joiner.toString();
  }

}

