/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Questionnaire Question.
 */
@JsonPropertyOrder({
  QuestionnaireQuestion.JSON_PROPERTY_ID,
  QuestionnaireQuestion.JSON_PROPERTY_IDENTIFIER,
  QuestionnaireQuestion.JSON_PROPERTY_SEQUENCE,
  QuestionnaireQuestion.JSON_PROPERTY_STATUS,
  QuestionnaireQuestion.JSON_PROPERTY_TEXT,
  QuestionnaireQuestion.JSON_PROPERTY_EXPLANATION,
  QuestionnaireQuestion.JSON_PROPERTY_FORMAT,
  QuestionnaireQuestion.JSON_PROPERTY_OPTIONS,
  QuestionnaireQuestion.JSON_PROPERTY_SCALE_MIN,
  QuestionnaireQuestion.JSON_PROPERTY_SCALE_MAX,
  QuestionnaireQuestion.JSON_PROPERTY_SCALE_STEP,
  QuestionnaireQuestion.JSON_PROPERTY_CREATED_AT,
  QuestionnaireQuestion.JSON_PROPERTY_UPDATED_AT
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class QuestionnaireQuestion {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_IDENTIFIER = "identifier";
  @jakarta.annotation.Nullable
  private String identifier;

  public static final String JSON_PROPERTY_SEQUENCE = "sequence";
  @jakarta.annotation.Nullable
  private Integer sequence;

  /**
   * Question status, could be active or disabled. Questions can be set to disabled and new questions created if a Partners elects to edit one or more of the questions presented to their Investors.
   */
  public enum StatusEnum {
    DISABLED(String.valueOf("DISABLED")),
    
    ACTIVE(String.valueOf("ACTIVE"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_TEXT = "text";
  @jakarta.annotation.Nullable
  private String text;

  public static final String JSON_PROPERTY_EXPLANATION = "explanation";
  @jakarta.annotation.Nullable
  private String explanation;

  /**
   * Format of the question.
   */
  public enum FormatEnum {
    INTEGER(String.valueOf("Integer")),
    
    FLOAT(String.valueOf("Float")),
    
    PERCENTAGE(String.valueOf("Percentage")),
    
    MULTIPLE_CHOICE_SINGLE(String.valueOf("MultipleChoiceSingle")),
    
    MULTIPLE_CHOICE_MULTIPLE(String.valueOf("MultipleChoiceMultiple")),
    
    BOOLEAN(String.valueOf("Boolean")),
    
    DATE(String.valueOf("Date")),
    
    TEXT(String.valueOf("Text")),
    
    EMAIL(String.valueOf("Email")),
    
    SCALE(String.valueOf("Scale"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nonnull
  private FormatEnum format;

  public static final String JSON_PROPERTY_OPTIONS = "options";
  @jakarta.annotation.Nullable
  private List<String> options;

  public static final String JSON_PROPERTY_SCALE_MIN = "scaleMin";
  @jakarta.annotation.Nullable
  private Integer scaleMin;

  public static final String JSON_PROPERTY_SCALE_MAX = "scaleMax";
  @jakarta.annotation.Nullable
  private Integer scaleMax;

  public static final String JSON_PROPERTY_SCALE_STEP = "scaleStep";
  @jakarta.annotation.Nullable
  private Integer scaleStep;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public QuestionnaireQuestion() {
  }

  public QuestionnaireQuestion id(@jakarta.annotation.Nullable UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID associated with a Questionnaire question.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }

  public QuestionnaireQuestion identifier(@jakarta.annotation.Nullable String identifier) {
    
    this.identifier = identifier;
    return this;
  }

  /**
   * Identifier for the question.
   * @return identifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIdentifier() {
    return identifier;
  }


  @JsonProperty(JSON_PROPERTY_IDENTIFIER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifier(@jakarta.annotation.Nullable String identifier) {
    this.identifier = identifier;
  }

  public QuestionnaireQuestion sequence(@jakarta.annotation.Nullable Integer sequence) {
    
    this.sequence = sequence;
    return this;
  }

  /**
   * Order sequence of the question within the Questionnaire.
   * @return sequence
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getSequence() {
    return sequence;
  }


  @JsonProperty(JSON_PROPERTY_SEQUENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSequence(@jakarta.annotation.Nullable Integer sequence) {
    this.sequence = sequence;
  }

  public QuestionnaireQuestion status(@jakarta.annotation.Nullable StatusEnum status) {
    
    this.status = status;
    return this;
  }

  /**
   * Question status, could be active or disabled. Questions can be set to disabled and new questions created if a Partners elects to edit one or more of the questions presented to their Investors.
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable StatusEnum status) {
    this.status = status;
  }

  public QuestionnaireQuestion text(@jakarta.annotation.Nullable String text) {
    
    this.text = text;
    return this;
  }

  /**
   * Text of the question.
   * @return text
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(@jakarta.annotation.Nullable String text) {
    this.text = text;
  }

  public QuestionnaireQuestion explanation(@jakarta.annotation.Nullable String explanation) {
    
    this.explanation = explanation;
    return this;
  }

  /**
   * An explanation of the question presented within a Questionnaire. Helps the Investor understand the question being asked by providing additional context.
   * @return explanation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExplanation() {
    return explanation;
  }


  @JsonProperty(JSON_PROPERTY_EXPLANATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExplanation(@jakarta.annotation.Nullable String explanation) {
    this.explanation = explanation;
  }

  public QuestionnaireQuestion format(@jakarta.annotation.Nonnull FormatEnum format) {
    
    this.format = format;
    return this;
  }

  /**
   * Format of the question.
   * @return format
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@jakarta.annotation.Nonnull FormatEnum format) {
    this.format = format;
  }

  public QuestionnaireQuestion options(@jakarta.annotation.Nullable List<String> options) {
    
    this.options = options;
    return this;
  }

  public QuestionnaireQuestion addOptionsItem(String optionsItem) {
    if (this.options == null) {
      this.options = new ArrayList<>();
    }
    this.options.add(optionsItem);
    return this;
  }

  /**
   * A list of potential answers associated with a question.
   * @return options
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getOptions() {
    return options;
  }


  @JsonProperty(JSON_PROPERTY_OPTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOptions(@jakarta.annotation.Nullable List<String> options) {
    this.options = options;
  }

  public QuestionnaireQuestion scaleMin(@jakarta.annotation.Nullable Integer scaleMin) {
    
    this.scaleMin = scaleMin;
    return this;
  }

  /**
   * Optional minimum value for a scale question.
   * @return scaleMin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCALE_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScaleMin() {
    return scaleMin;
  }


  @JsonProperty(JSON_PROPERTY_SCALE_MIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScaleMin(@jakarta.annotation.Nullable Integer scaleMin) {
    this.scaleMin = scaleMin;
  }

  public QuestionnaireQuestion scaleMax(@jakarta.annotation.Nullable Integer scaleMax) {
    
    this.scaleMax = scaleMax;
    return this;
  }

  /**
   * Optional maximum value for a scale question.
   * @return scaleMax
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCALE_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScaleMax() {
    return scaleMax;
  }


  @JsonProperty(JSON_PROPERTY_SCALE_MAX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScaleMax(@jakarta.annotation.Nullable Integer scaleMax) {
    this.scaleMax = scaleMax;
  }

  public QuestionnaireQuestion scaleStep(@jakarta.annotation.Nullable Integer scaleStep) {
    
    this.scaleStep = scaleStep;
    return this;
  }

  /**
   * Optional step value for a scale question.
   * @return scaleStep
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCALE_STEP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getScaleStep() {
    return scaleStep;
  }


  @JsonProperty(JSON_PROPERTY_SCALE_STEP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScaleStep(@jakarta.annotation.Nullable Integer scaleStep) {
    this.scaleStep = scaleStep;
  }

  public QuestionnaireQuestion createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Created at the specified date.
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public QuestionnaireQuestion updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Updated at the specified date.
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuestionnaireQuestion questionnaireQuestion = (QuestionnaireQuestion) o;
    return Objects.equals(this.id, questionnaireQuestion.id) &&
        Objects.equals(this.identifier, questionnaireQuestion.identifier) &&
        Objects.equals(this.sequence, questionnaireQuestion.sequence) &&
        Objects.equals(this.status, questionnaireQuestion.status) &&
        Objects.equals(this.text, questionnaireQuestion.text) &&
        Objects.equals(this.explanation, questionnaireQuestion.explanation) &&
        Objects.equals(this.format, questionnaireQuestion.format) &&
        Objects.equals(this.options, questionnaireQuestion.options) &&
        Objects.equals(this.scaleMin, questionnaireQuestion.scaleMin) &&
        Objects.equals(this.scaleMax, questionnaireQuestion.scaleMax) &&
        Objects.equals(this.scaleStep, questionnaireQuestion.scaleStep) &&
        Objects.equals(this.createdAt, questionnaireQuestion.createdAt) &&
        Objects.equals(this.updatedAt, questionnaireQuestion.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, identifier, sequence, status, text, explanation, format, options, scaleMin, scaleMax, scaleStep, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuestionnaireQuestion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    explanation: ").append(toIndentedString(explanation)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    options: ").append(toIndentedString(options)).append("\n");
    sb.append("    scaleMin: ").append(toIndentedString(scaleMin)).append("\n");
    sb.append("    scaleMax: ").append(toIndentedString(scaleMax)).append("\n");
    sb.append("    scaleStep: ").append(toIndentedString(scaleStep)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `identifier` to the URL query string
    if (getIdentifier() != null) {
      try {
        joiner.add(String.format("%sidentifier%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIdentifier()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sequence` to the URL query string
    if (getSequence() != null) {
      try {
        joiner.add(String.format("%ssequence%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSequence()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      try {
        joiner.add(String.format("%sstatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `text` to the URL query string
    if (getText() != null) {
      try {
        joiner.add(String.format("%stext%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getText()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `explanation` to the URL query string
    if (getExplanation() != null) {
      try {
        joiner.add(String.format("%sexplanation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExplanation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `format` to the URL query string
    if (getFormat() != null) {
      try {
        joiner.add(String.format("%sformat%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFormat()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `options` to the URL query string
    if (getOptions() != null) {
      for (int i = 0; i < getOptions().size(); i++) {
        try {
          joiner.add(String.format("%soptions%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getOptions().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `scaleMin` to the URL query string
    if (getScaleMin() != null) {
      try {
        joiner.add(String.format("%sscaleMin%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScaleMin()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `scaleMax` to the URL query string
    if (getScaleMax() != null) {
      try {
        joiner.add(String.format("%sscaleMax%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScaleMax()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `scaleStep` to the URL query string
    if (getScaleStep() != null) {
      try {
        joiner.add(String.format("%sscaleStep%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getScaleStep()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `updatedAt` to the URL query string
    if (getUpdatedAt() != null) {
      try {
        joiner.add(String.format("%supdatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

