/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.88
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * Create Investor represnts the information required to create the investor in the primary offering.
 */
@JsonPropertyOrder({
  UpdateInvestor.JSON_PROPERTY_ID,
  UpdateInvestor.JSON_PROPERTY_INVESTOR_REFERENCE_ID,
  UpdateInvestor.JSON_PROPERTY_INDIVIDUAL_INVESTOR,
  UpdateInvestor.JSON_PROPERTY_ENTITY_INVESTOR,
  UpdateInvestor.JSON_PROPERTY_FINANCIAL_ADVISOR_ID
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class UpdateInvestor {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_INVESTOR_REFERENCE_ID = "investorReferenceId";
  @jakarta.annotation.Nonnull
  private String investorReferenceId;

  public static final String JSON_PROPERTY_INDIVIDUAL_INVESTOR = "individualInvestor";
  @jakarta.annotation.Nullable
  private ModifyIndividualInvestor individualInvestor;

  public static final String JSON_PROPERTY_ENTITY_INVESTOR = "entityInvestor";
  @jakarta.annotation.Nullable
  private UpdateEntityInvestor entityInvestor;

  public static final String JSON_PROPERTY_FINANCIAL_ADVISOR_ID = "financialAdvisorId";
  @jakarta.annotation.Nullable
  private UUID financialAdvisorId;

  public UpdateInvestor() {
  }

  public UpdateInvestor id(@jakarta.annotation.Nonnull UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@jakarta.annotation.Nonnull UUID id) {
    this.id = id;
  }

  public UpdateInvestor investorReferenceId(@jakarta.annotation.Nonnull String investorReferenceId) {
    
    this.investorReferenceId = investorReferenceId;
    return this;
  }

  /**
   * Represents the unique ID provided by a Partner, used to identify an Investor.
   * @return investorReferenceId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVESTOR_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInvestorReferenceId() {
    return investorReferenceId;
  }


  @JsonProperty(JSON_PROPERTY_INVESTOR_REFERENCE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvestorReferenceId(@jakarta.annotation.Nonnull String investorReferenceId) {
    this.investorReferenceId = investorReferenceId;
  }

  public UpdateInvestor individualInvestor(@jakarta.annotation.Nullable ModifyIndividualInvestor individualInvestor) {
    
    this.individualInvestor = individualInvestor;
    return this;
  }

  /**
   * Information about the individual investor if this Investor is of that type.
   * @return individualInvestor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ModifyIndividualInvestor getIndividualInvestor() {
    return individualInvestor;
  }


  @JsonProperty(JSON_PROPERTY_INDIVIDUAL_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndividualInvestor(@jakarta.annotation.Nullable ModifyIndividualInvestor individualInvestor) {
    this.individualInvestor = individualInvestor;
  }

  public UpdateInvestor entityInvestor(@jakarta.annotation.Nullable UpdateEntityInvestor entityInvestor) {
    
    this.entityInvestor = entityInvestor;
    return this;
  }

  /**
   * Information about the entity investor if this Investor is of that type.
   * @return entityInvestor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UpdateEntityInvestor getEntityInvestor() {
    return entityInvestor;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_INVESTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntityInvestor(@jakarta.annotation.Nullable UpdateEntityInvestor entityInvestor) {
    this.entityInvestor = entityInvestor;
  }

  public UpdateInvestor financialAdvisorId(@jakarta.annotation.Nullable UUID financialAdvisorId) {
    
    this.financialAdvisorId = financialAdvisorId;
    return this;
  }

  /**
   * The Financial Advisor ID associated with the Investor.
   * @return financialAdvisorId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINANCIAL_ADVISOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getFinancialAdvisorId() {
    return financialAdvisorId;
  }


  @JsonProperty(JSON_PROPERTY_FINANCIAL_ADVISOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancialAdvisorId(@jakarta.annotation.Nullable UUID financialAdvisorId) {
    this.financialAdvisorId = financialAdvisorId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateInvestor updateInvestor = (UpdateInvestor) o;
    return Objects.equals(this.id, updateInvestor.id) &&
        Objects.equals(this.investorReferenceId, updateInvestor.investorReferenceId) &&
        Objects.equals(this.individualInvestor, updateInvestor.individualInvestor) &&
        Objects.equals(this.entityInvestor, updateInvestor.entityInvestor) &&
        Objects.equals(this.financialAdvisorId, updateInvestor.financialAdvisorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, investorReferenceId, individualInvestor, entityInvestor, financialAdvisorId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateInvestor {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    investorReferenceId: ").append(toIndentedString(investorReferenceId)).append("\n");
    sb.append("    individualInvestor: ").append(toIndentedString(individualInvestor)).append("\n");
    sb.append("    entityInvestor: ").append(toIndentedString(entityInvestor)).append("\n");
    sb.append("    financialAdvisorId: ").append(toIndentedString(financialAdvisorId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `investorReferenceId` to the URL query string
    if (getInvestorReferenceId() != null) {
      try {
        joiner.add(String.format("%sinvestorReferenceId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getInvestorReferenceId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `individualInvestor` to the URL query string
    if (getIndividualInvestor() != null) {
      joiner.add(getIndividualInvestor().toUrlQueryString(prefix + "individualInvestor" + suffix));
    }

    // add `entityInvestor` to the URL query string
    if (getEntityInvestor() != null) {
      joiner.add(getEntityInvestor().toUrlQueryString(prefix + "entityInvestor" + suffix));
    }

    // add `financialAdvisorId` to the URL query string
    if (getFinancialAdvisorId() != null) {
      try {
        joiner.add(String.format("%sfinancialAdvisorId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFinancialAdvisorId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

