/*
 * Primary Offering API
 * Primary Offering API
 *
 * The version of the OpenAPI document: 1.1.108
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.monarkmarkets.api.primary.webapi.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.StringJoiner;
import java.util.UUID;

/**
 * WebhookEvent
 */
@JsonPropertyOrder({
  WebhookEvent.JSON_PROPERTY_ID,
  WebhookEvent.JSON_PROPERTY_WEBHOOK_ID,
  WebhookEvent.JSON_PROPERTY_DELIVERY_STATUS,
  WebhookEvent.JSON_PROPERTY_EVENT_TYPE,
  WebhookEvent.JSON_PROPERTY_DATA,
  WebhookEvent.JSON_PROPERTY_CREATED_AT,
  WebhookEvent.JSON_PROPERTY_DELIVERED_AT
})
@JsonInclude(JsonInclude.Include.NON_NULL)
@lombok.Builder
@lombok.AllArgsConstructor
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.13.0")
public class WebhookEvent {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_WEBHOOK_ID = "webhookId";
  @jakarta.annotation.Nullable
  private UUID webhookId;

  /**
   * Created at the specified date.
   */
  public enum DeliveryStatusEnum {
    PENDING(String.valueOf("Pending")),
    
    DELIVERED(String.valueOf("Delivered")),
    
    FAILED(String.valueOf("Failed"));

    private String value;

    DeliveryStatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DeliveryStatusEnum fromValue(String value) {
      for (DeliveryStatusEnum b : DeliveryStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DELIVERY_STATUS = "deliveryStatus";
  @jakarta.annotation.Nullable
  private DeliveryStatusEnum deliveryStatus;

  /**
   * The type of webhook event.
   */
  public enum EventTypeEnum {
    PRE_IPO_COMPANY(String.valueOf("PreIPOCompany")),
    
    PRE_IPO_COMPANY_INVESTMENT(String.valueOf("PreIPOCompanyInvestment")),
    
    PRE_IPO_COMPANY_SPV(String.valueOf("PreIPOCompanySPV")),
    
    INVESTOR(String.valueOf("Investor")),
    
    DOCUMENT(String.valueOf("Document")),
    
    INVESTOR_SUBSCRIPTION_ACTION(String.valueOf("InvestorSubscriptionAction")),
    
    SUBSCRIPTION_STATUS(String.valueOf("SubscriptionStatus"));

    private String value;

    EventTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static EventTypeEnum fromValue(String value) {
      for (EventTypeEnum b : EventTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EVENT_TYPE = "eventType";
  @jakarta.annotation.Nullable
  private EventTypeEnum eventType;

  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nullable
  private String data;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_DELIVERED_AT = "deliveredAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deliveredAt;

  public WebhookEvent() {
  }

  public WebhookEvent id(@jakarta.annotation.Nullable UUID id) {
    
    this.id = id;
    return this;
  }

  /**
   * Unique ID associated with a WebhookEvent.
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable UUID id) {
    this.id = id;
  }

  public WebhookEvent webhookId(@jakarta.annotation.Nullable UUID webhookId) {
    
    this.webhookId = webhookId;
    return this;
  }

  /**
   * Created at the specified date.
   * @return webhookId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBHOOK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getWebhookId() {
    return webhookId;
  }


  @JsonProperty(JSON_PROPERTY_WEBHOOK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWebhookId(@jakarta.annotation.Nullable UUID webhookId) {
    this.webhookId = webhookId;
  }

  public WebhookEvent deliveryStatus(@jakarta.annotation.Nullable DeliveryStatusEnum deliveryStatus) {
    
    this.deliveryStatus = deliveryStatus;
    return this;
  }

  /**
   * Created at the specified date.
   * @return deliveryStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DeliveryStatusEnum getDeliveryStatus() {
    return deliveryStatus;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryStatus(@jakarta.annotation.Nullable DeliveryStatusEnum deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }

  public WebhookEvent eventType(@jakarta.annotation.Nullable EventTypeEnum eventType) {
    
    this.eventType = eventType;
    return this;
  }

  /**
   * The type of webhook event.
   * @return eventType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EventTypeEnum getEventType() {
    return eventType;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventType(@jakarta.annotation.Nullable EventTypeEnum eventType) {
    this.eventType = eventType;
  }

  public WebhookEvent data(@jakarta.annotation.Nullable String data) {
    
    this.data = data;
    return this;
  }

  /**
   * The Webhook Event data.
   * @return data
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@jakarta.annotation.Nullable String data) {
    this.data = data;
  }

  public WebhookEvent createdAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Created at the specified date.
   * @return createdAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@jakarta.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public WebhookEvent deliveredAt(@jakarta.annotation.Nullable OffsetDateTime deliveredAt) {
    
    this.deliveredAt = deliveredAt;
    return this;
  }

  /**
   * Delivered at the specified date.
   * @return deliveredAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELIVERED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeliveredAt() {
    return deliveredAt;
  }


  @JsonProperty(JSON_PROPERTY_DELIVERED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveredAt(@jakarta.annotation.Nullable OffsetDateTime deliveredAt) {
    this.deliveredAt = deliveredAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEvent webhookEvent = (WebhookEvent) o;
    return Objects.equals(this.id, webhookEvent.id) &&
        Objects.equals(this.webhookId, webhookEvent.webhookId) &&
        Objects.equals(this.deliveryStatus, webhookEvent.deliveryStatus) &&
        Objects.equals(this.eventType, webhookEvent.eventType) &&
        Objects.equals(this.data, webhookEvent.data) &&
        Objects.equals(this.createdAt, webhookEvent.createdAt) &&
        Objects.equals(this.deliveredAt, webhookEvent.deliveredAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, webhookId, deliveryStatus, eventType, data, createdAt, deliveredAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEvent {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    webhookId: ").append(toIndentedString(webhookId)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    deliveredAt: ").append(toIndentedString(deliveredAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `webhookId` to the URL query string
    if (getWebhookId() != null) {
      try {
        joiner.add(String.format("%swebhookId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWebhookId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deliveryStatus` to the URL query string
    if (getDeliveryStatus() != null) {
      try {
        joiner.add(String.format("%sdeliveryStatus%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeliveryStatus()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `eventType` to the URL query string
    if (getEventType() != null) {
      try {
        joiner.add(String.format("%seventType%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getEventType()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `data` to the URL query string
    if (getData() != null) {
      try {
        joiner.add(String.format("%sdata%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getData()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `createdAt` to the URL query string
    if (getCreatedAt() != null) {
      try {
        joiner.add(String.format("%screatedAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreatedAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deliveredAt` to the URL query string
    if (getDeliveredAt() != null) {
      try {
        joiner.add(String.format("%sdeliveredAt%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeliveredAt()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

